#!/usr/bin/env python3
"""Generate the checked-in Rust atlas from Chafa's LGPL symbol definitions."""

from pathlib import Path
import re
import unicodedata

ROOT = Path(__file__).resolve().parents[1]
INTERNAL = ROOT / "vendor/chafa/internal"
HEADERS = [
    "chafa-symbols-ascii.h", "chafa-symbols-latin.h", "chafa-symbols-block.h",
    "chafa-symbols-kana.h", "chafa-symbols-misc-narrow.h",
]

ENTRY = re.compile(
    r"\{\s*(?:/\*.*?\*/\s*)*(CHAFA_SYMBOL_TAG_[A-Z0-9_| \t\r\n]+),\s*(0x[0-9a-fA-F]+),\s*"
    r"CHAFA_SYMBOL_OUTLINE_(8X8|16X8)\s*\((.*?)\)\s*\}", re.S)
STRING = re.compile(r'"([ X]+)"')


def bitmap(bits):
    value = 0
    for bit in bits:
        value = (value << 1) | bool(bit)
    return value


def printable_ltr(cp):
    ch = chr(cp)
    return (cp == 0x20 or ch.isprintable()) and unicodedata.bidirectional(ch) not in {"R", "AL"}


def explicit_symbols():
    result = []
    for name in HEADERS:
        text = (INTERNAL / name).read_text()
        for tags, cp_text, width, body in ENTRY.findall(text):
            cp = int(cp_text, 16)
            outline = "".join(STRING.findall(body))
            if width != "8X8" or len(outline) != 64:
                continue
            if "_WIDE" in tags or "_AMBIGUOUS" in tags or "_UGLY" in tags or "_EXTRA" in tags:
                continue
            if not printable_ltr(cp):
                continue
            # Chafa auto-excludes these emoji/meta ranges as ugly.
            if 0x2600 <= cp <= 0x26ff or 0x1f000 <= cp <= 0x1fb3b or 0x1fbcb <= cp <= 0x1ffff:
                continue
            result.append((cp, bitmap(c != " " for c in outline)))
    return result


def braille():
    for value in range(256):
        cov = [0] * 64
        for bit, (x, y) in enumerate(((1,0),(1,2),(1,4),(5,0),(5,2),(5,4),(1,6),(5,6))):
            for dx in range(2):
                if value & (1 << bit): cov[(y * 8) + x + dx] = 1
        yield 0x2800 + value, bitmap(cov)


def sextants():
    for cp in range(0x1fb00, 0x1fb3b):
        val = cp - 0x1fb00 + 1
        if val > 20: val += 1
        if val > 41: val += 1
        cov = [0] * 64
        for y in range(3):
            for x in range(2):
                if val & (1 << (y * 2 + x)):
                    for v in range(3):
                        row = y * 3 + v
                        if row > 3: row -= 1
                        for u in range(4): cov[row * 8 + x * 4 + u] = 1
        yield cp, bitmap(cov)


def main():
    symbols = explicit_symbols() + list(braille()) + list(sextants())
    # The map is searched in increasing coverage order in Chafa.
    symbols = sorted(set(symbols), key=lambda item: (item[1].bit_count(), item[0]))
    lines = [
        "// Generated by tools/generate_symbols.py from upstream Chafa's LGPL atlas.",
        "// Do not edit by hand.",
        "#[derive(Clone, Copy, Debug)]",
        "pub struct Symbol { pub ch: char, pub bitmap: u64 }",
        "pub const SYMBOLS: &[Symbol] = &[",
    ]
    for cp, mask in symbols:
        lines.append(f"    Symbol {{ ch: '\\u{{{cp:x}}}', bitmap: 0x{mask:016x} }},")
    lines.append("];\n")
    (ROOT / "src/symbols.rs").write_text("\n".join(lines))
    print(f"generated {len(symbols)} narrow symbols")


if __name__ == "__main__":
    main()
