// Generated by tools/generate_symbols.py from upstream Chafa's LGPL atlas.
// Do not edit by hand.
#[derive(Clone, Copy, Debug)]
pub struct Symbol {
    pub ch: char,
    pub bitmap: u64,
}
pub const SYMBOLS: &[Symbol] = &[
    Symbol {
        ch: '\u{20}',
        bitmap: 0x0000000000000000,
    },
    Symbol {
        ch: '\u{2800}',
        bitmap: 0x0000000000000000,
    },
    Symbol {
        ch: '\u{2e}',
        bitmap: 0x0000000000001000,
    },
    Symbol {
        ch: '\u{2d9}',
        bitmap: 0x1000000000000000,
    },
    Symbol {
        ch: '\u{387}',
        bitmap: 0x0000001000000000,
    },
    Symbol {
        ch: '\u{27}',
        bitmap: 0x1010000000000000,
    },
    Symbol {
        ch: '\u{2c}',
        bitmap: 0x0000000000001020,
    },
    Symbol {
        ch: '\u{3a}',
        bitmap: 0x0000001000001000,
    },
    Symbol {
        ch: '\u{60}',
        bitmap: 0x1800000000000000,
    },
    Symbol {
        ch: '\u{a8}',
        bitmap: 0x2400000000000000,
    },
    Symbol {
        ch: '\u{b4}',
        bitmap: 0x1800000000000000,
    },
    Symbol {
        ch: '\u{b7}',
        bitmap: 0x0000001010000000,
    },
    Symbol {
        ch: '\u{b8}',
        bitmap: 0x0000000000001020,
    },
    Symbol {
        ch: '\u{2bb}',
        bitmap: 0x0810000000000000,
    },
    Symbol {
        ch: '\u{2bc}',
        bitmap: 0x0810000000000000,
    },
    Symbol {
        ch: '\u{2bd}',
        bitmap: 0x1008000000000000,
    },
    Symbol {
        ch: '\u{384}',
        bitmap: 0xc000000000000000,
    },
    Symbol {
        ch: '\u{2801}',
        bitmap: 0x6000000000000000,
    },
    Symbol {
        ch: '\u{2802}',
        bitmap: 0x0000600000000000,
    },
    Symbol {
        ch: '\u{2804}',
        bitmap: 0x0000000060000000,
    },
    Symbol {
        ch: '\u{2808}',
        bitmap: 0x0600000000000000,
    },
    Symbol {
        ch: '\u{2810}',
        bitmap: 0x0000060000000000,
    },
    Symbol {
        ch: '\u{2820}',
        bitmap: 0x0000000006000000,
    },
    Symbol {
        ch: '\u{2840}',
        bitmap: 0x0000000000006000,
    },
    Symbol {
        ch: '\u{2880}',
        bitmap: 0x0000000000000600,
    },
    Symbol {
        ch: '\u{3b}',
        bitmap: 0x0000001000001020,
    },
    Symbol {
        ch: '\u{22}',
        bitmap: 0x2424000000000000,
    },
    Symbol {
        ch: '\u{af}',
        bitmap: 0x3c00000000000000,
    },
    Symbol {
        ch: '\u{2c6}',
        bitmap: 0x1824000000000000,
    },
    Symbol {
        ch: '\u{2c7}',
        bitmap: 0x2418000000000000,
    },
    Symbol {
        ch: '\u{2d8}',
        bitmap: 0x2418000000000000,
    },
    Symbol {
        ch: '\u{2db}',
        bitmap: 0x000000000000040e,
    },
    Symbol {
        ch: '\u{2dd}',
        bitmap: 0x3600000000000000,
    },
    Symbol {
        ch: '\u{2508}',
        bitmap: 0x00000000aa000000,
    },
    Symbol {
        ch: '\u{250a}',
        bitmap: 0x0800080008000800,
    },
    Symbol {
        ch: '\u{2574}',
        bitmap: 0x00000000f0000000,
    },
    Symbol {
        ch: '\u{2575}',
        bitmap: 0x0808080800000000,
    },
    Symbol {
        ch: '\u{2576}',
        bitmap: 0x000000000f000000,
    },
    Symbol {
        ch: '\u{2577}',
        bitmap: 0x0000000008080808,
    },
    Symbol {
        ch: '\u{2803}',
        bitmap: 0x6000600000000000,
    },
    Symbol {
        ch: '\u{2805}',
        bitmap: 0x6000000060000000,
    },
    Symbol {
        ch: '\u{2806}',
        bitmap: 0x0000600060000000,
    },
    Symbol {
        ch: '\u{2809}',
        bitmap: 0x6600000000000000,
    },
    Symbol {
        ch: '\u{280a}',
        bitmap: 0x0600600000000000,
    },
    Symbol {
        ch: '\u{280c}',
        bitmap: 0x0600000060000000,
    },
    Symbol {
        ch: '\u{2811}',
        bitmap: 0x6000060000000000,
    },
    Symbol {
        ch: '\u{2812}',
        bitmap: 0x0000660000000000,
    },
    Symbol {
        ch: '\u{2814}',
        bitmap: 0x0000060060000000,
    },
    Symbol {
        ch: '\u{2818}',
        bitmap: 0x0600060000000000,
    },
    Symbol {
        ch: '\u{2821}',
        bitmap: 0x6000000006000000,
    },
    Symbol {
        ch: '\u{2822}',
        bitmap: 0x0000600006000000,
    },
    Symbol {
        ch: '\u{2824}',
        bitmap: 0x0000000066000000,
    },
    Symbol {
        ch: '\u{2828}',
        bitmap: 0x0600000006000000,
    },
    Symbol {
        ch: '\u{2830}',
        bitmap: 0x0000060006000000,
    },
    Symbol {
        ch: '\u{2841}',
        bitmap: 0x6000000000006000,
    },
    Symbol {
        ch: '\u{2842}',
        bitmap: 0x0000600000006000,
    },
    Symbol {
        ch: '\u{2844}',
        bitmap: 0x0000000060006000,
    },
    Symbol {
        ch: '\u{2848}',
        bitmap: 0x0600000000006000,
    },
    Symbol {
        ch: '\u{2850}',
        bitmap: 0x0000060000006000,
    },
    Symbol {
        ch: '\u{2860}',
        bitmap: 0x0000000006006000,
    },
    Symbol {
        ch: '\u{2881}',
        bitmap: 0x6000000000000600,
    },
    Symbol {
        ch: '\u{2882}',
        bitmap: 0x0000600000000600,
    },
    Symbol {
        ch: '\u{2884}',
        bitmap: 0x0000000060000600,
    },
    Symbol {
        ch: '\u{2888}',
        bitmap: 0x0600000000000600,
    },
    Symbol {
        ch: '\u{2890}',
        bitmap: 0x0000060000000600,
    },
    Symbol {
        ch: '\u{28a0}',
        bitmap: 0x0000000006000600,
    },
    Symbol {
        ch: '\u{28c0}',
        bitmap: 0x0000000000006600,
    },
    Symbol {
        ch: '\u{1fba0}',
        bitmap: 0x1020408000000000,
    },
    Symbol {
        ch: '\u{1fba1}',
        bitmap: 0x0804020100000000,
    },
    Symbol {
        ch: '\u{1fba2}',
        bitmap: 0x0000000080402010,
    },
    Symbol {
        ch: '\u{1fba3}',
        bitmap: 0x0000000001020408,
    },
    Symbol {
        ch: '\u{21}',
        bitmap: 0x0010101010001000,
    },
    Symbol {
        ch: '\u{5e}',
        bitmap: 0x1028440000000000,
    },
    Symbol {
        ch: '\u{a1}',
        bitmap: 0x0010001010101000,
    },
    Symbol {
        ch: '\u{a6}',
        bitmap: 0x0010101000101000,
    },
    Symbol {
        ch: '\u{2d}',
        bitmap: 0x000000007e000000,
    },
    Symbol {
        ch: '\u{5f}',
        bitmap: 0x000000000000007e,
    },
    Symbol {
        ch: '\u{7c}',
        bitmap: 0x0010101010101000,
    },
    Symbol {
        ch: '\u{b0}',
        bitmap: 0x1824180000000000,
    },
    Symbol {
        ch: '\u{2dc}',
        bitmap: 0x324c000000000000,
    },
    Symbol {
        ch: '\u{385}',
        bitmap: 0x0834240000000000,
    },
    Symbol {
        ch: '\u{3b9}',
        bitmap: 0x0000003010100c00,
    },
    Symbol {
        ch: '\u{2504}',
        bitmap: 0x00000000db000000,
    },
    Symbol {
        ch: '\u{2506}',
        bitmap: 0x0808000808000808,
    },
    Symbol {
        ch: '\u{254c}',
        bitmap: 0x00000000e7000000,
    },
    Symbol {
        ch: '\u{254e}',
        bitmap: 0x0808080000080808,
    },
    Symbol {
        ch: '\u{2807}',
        bitmap: 0x6000600060000000,
    },
    Symbol {
        ch: '\u{280b}',
        bitmap: 0x6600600000000000,
    },
    Symbol {
        ch: '\u{280d}',
        bitmap: 0x6600000060000000,
    },
    Symbol {
        ch: '\u{280e}',
        bitmap: 0x0600600060000000,
    },
    Symbol {
        ch: '\u{2813}',
        bitmap: 0x6000660000000000,
    },
    Symbol {
        ch: '\u{2815}',
        bitmap: 0x6000060060000000,
    },
    Symbol {
        ch: '\u{2816}',
        bitmap: 0x0000660060000000,
    },
    Symbol {
        ch: '\u{2819}',
        bitmap: 0x6600060000000000,
    },
    Symbol {
        ch: '\u{281a}',
        bitmap: 0x0600660000000000,
    },
    Symbol {
        ch: '\u{281c}',
        bitmap: 0x0600060060000000,
    },
    Symbol {
        ch: '\u{2823}',
        bitmap: 0x6000600006000000,
    },
    Symbol {
        ch: '\u{2825}',
        bitmap: 0x6000000066000000,
    },
    Symbol {
        ch: '\u{2826}',
        bitmap: 0x0000600066000000,
    },
    Symbol {
        ch: '\u{2829}',
        bitmap: 0x6600000006000000,
    },
    Symbol {
        ch: '\u{282a}',
        bitmap: 0x0600600006000000,
    },
    Symbol {
        ch: '\u{282c}',
        bitmap: 0x0600000066000000,
    },
    Symbol {
        ch: '\u{2831}',
        bitmap: 0x6000060006000000,
    },
    Symbol {
        ch: '\u{2832}',
        bitmap: 0x0000660006000000,
    },
    Symbol {
        ch: '\u{2834}',
        bitmap: 0x0000060066000000,
    },
    Symbol {
        ch: '\u{2838}',
        bitmap: 0x0600060006000000,
    },
    Symbol {
        ch: '\u{2843}',
        bitmap: 0x6000600000006000,
    },
    Symbol {
        ch: '\u{2845}',
        bitmap: 0x6000000060006000,
    },
    Symbol {
        ch: '\u{2846}',
        bitmap: 0x0000600060006000,
    },
    Symbol {
        ch: '\u{2849}',
        bitmap: 0x6600000000006000,
    },
    Symbol {
        ch: '\u{284a}',
        bitmap: 0x0600600000006000,
    },
    Symbol {
        ch: '\u{284c}',
        bitmap: 0x0600000060006000,
    },
    Symbol {
        ch: '\u{2851}',
        bitmap: 0x6000060000006000,
    },
    Symbol {
        ch: '\u{2852}',
        bitmap: 0x0000660000006000,
    },
    Symbol {
        ch: '\u{2854}',
        bitmap: 0x0000060060006000,
    },
    Symbol {
        ch: '\u{2858}',
        bitmap: 0x0600060000006000,
    },
    Symbol {
        ch: '\u{2861}',
        bitmap: 0x6000000006006000,
    },
    Symbol {
        ch: '\u{2862}',
        bitmap: 0x0000600006006000,
    },
    Symbol {
        ch: '\u{2864}',
        bitmap: 0x0000000066006000,
    },
    Symbol {
        ch: '\u{2868}',
        bitmap: 0x0600000006006000,
    },
    Symbol {
        ch: '\u{2870}',
        bitmap: 0x0000060006006000,
    },
    Symbol {
        ch: '\u{2883}',
        bitmap: 0x6000600000000600,
    },
    Symbol {
        ch: '\u{2885}',
        bitmap: 0x6000000060000600,
    },
    Symbol {
        ch: '\u{2886}',
        bitmap: 0x0000600060000600,
    },
    Symbol {
        ch: '\u{2889}',
        bitmap: 0x6600000000000600,
    },
    Symbol {
        ch: '\u{288a}',
        bitmap: 0x0600600000000600,
    },
    Symbol {
        ch: '\u{288c}',
        bitmap: 0x0600000060000600,
    },
    Symbol {
        ch: '\u{2891}',
        bitmap: 0x6000060000000600,
    },
    Symbol {
        ch: '\u{2892}',
        bitmap: 0x0000660000000600,
    },
    Symbol {
        ch: '\u{2894}',
        bitmap: 0x0000060060000600,
    },
    Symbol {
        ch: '\u{2898}',
        bitmap: 0x0600060000000600,
    },
    Symbol {
        ch: '\u{28a1}',
        bitmap: 0x6000000006000600,
    },
    Symbol {
        ch: '\u{28a2}',
        bitmap: 0x0000600006000600,
    },
    Symbol {
        ch: '\u{28a4}',
        bitmap: 0x0000000066000600,
    },
    Symbol {
        ch: '\u{28a8}',
        bitmap: 0x0600000006000600,
    },
    Symbol {
        ch: '\u{28b0}',
        bitmap: 0x0000060006000600,
    },
    Symbol {
        ch: '\u{28c1}',
        bitmap: 0x6000000000006600,
    },
    Symbol {
        ch: '\u{28c2}',
        bitmap: 0x0000600000006600,
    },
    Symbol {
        ch: '\u{28c4}',
        bitmap: 0x0000000060006600,
    },
    Symbol {
        ch: '\u{28c8}',
        bitmap: 0x0600000000006600,
    },
    Symbol {
        ch: '\u{28d0}',
        bitmap: 0x0000060000006600,
    },
    Symbol {
        ch: '\u{28e0}',
        bitmap: 0x0000000006006600,
    },
    Symbol {
        ch: '\u{2b}',
        bitmap: 0x000000107c100000,
    },
    Symbol {
        ch: '\u{7e}',
        bitmap: 0x629c000000000000,
    },
    Symbol {
        ch: '\u{ac}',
        bitmap: 0x0000007e02000000,
    },
    Symbol {
        ch: '\u{b9}',
        bitmap: 0x1030103800000000,
    },
    Symbol {
        ch: '\u{131}',
        bitmap: 0x0000003010103800,
    },
    Symbol {
        ch: '\u{250c}',
        bitmap: 0x000000000f080808,
    },
    Symbol {
        ch: '\u{1fb62}',
        bitmap: 0x0f03010000000000,
    },
    Symbol {
        ch: '\u{28}',
        bitmap: 0x0018202020201800,
    },
    Symbol {
        ch: '\u{29}',
        bitmap: 0x0030080808083000,
    },
    Symbol {
        ch: '\u{2f}',
        bitmap: 0x0004081830204000,
    },
    Symbol {
        ch: '\u{5c}',
        bitmap: 0x0040203018080400,
    },
    Symbol {
        ch: '\u{69}',
        bitmap: 0x0010003010103800,
    },
    Symbol {
        ch: '\u{7b}',
        bitmap: 0x000c102010100c00,
    },
    Symbol {
        ch: '\u{7d}',
        bitmap: 0x0030080408083000,
    },
    Symbol {
        ch: '\u{f7}',
        bitmap: 0x000010107c100000,
    },
    Symbol {
        ch: '\u{17f}',
        bitmap: 0x000e101010101000,
    },
    Symbol {
        ch: '\u{3af}',
        bitmap: 0x0008103010100c00,
    },
    Symbol {
        ch: '\u{3b3}',
        bitmap: 0x0000008244281010,
    },
    Symbol {
        ch: '\u{3ca}',
        bitmap: 0x0048003010100c00,
    },
    Symbol {
        ch: '\u{23ba}',
        bitmap: 0x00ff000000000000,
    },
    Symbol {
        ch: '\u{23bb}',
        bitmap: 0x000000ff00000000,
    },
    Symbol {
        ch: '\u{23bc}',
        bitmap: 0x00000000ff000000,
    },
    Symbol {
        ch: '\u{23bd}',
        bitmap: 0x000000000000ff00,
    },
    Symbol {
        ch: '\u{2500}',
        bitmap: 0x00000000ff000000,
    },
    Symbol {
        ch: '\u{2502}',
        bitmap: 0x0808080808080808,
    },
    Symbol {
        ch: '\u{2509}',
        bitmap: 0x000000aaaa000000,
    },
    Symbol {
        ch: '\u{250b}',
        bitmap: 0x1800180018001800,
    },
    Symbol {
        ch: '\u{2510}',
        bitmap: 0x00000000f8080808,
    },
    Symbol {
        ch: '\u{2514}',
        bitmap: 0x080808080f000000,
    },
    Symbol {
        ch: '\u{2571}',
        bitmap: 0x0102040810204080,
    },
    Symbol {
        ch: '\u{2572}',
        bitmap: 0x8040201008040201,
    },
    Symbol {
        ch: '\u{2578}',
        bitmap: 0x000000f0f0000000,
    },
    Symbol {
        ch: '\u{2579}',
        bitmap: 0x1818181800000000,
    },
    Symbol {
        ch: '\u{257a}',
        bitmap: 0x0000000f0f000000,
    },
    Symbol {
        ch: '\u{257b}',
        bitmap: 0x0000000018181818,
    },
    Symbol {
        ch: '\u{2581}',
        bitmap: 0x00000000000000ff,
    },
    Symbol {
        ch: '\u{258f}',
        bitmap: 0x8080808080808080,
    },
    Symbol {
        ch: '\u{2594}',
        bitmap: 0xff00000000000000,
    },
    Symbol {
        ch: '\u{2595}',
        bitmap: 0x0101010101010101,
    },
    Symbol {
        ch: '\u{280f}',
        bitmap: 0x6600600060000000,
    },
    Symbol {
        ch: '\u{2817}',
        bitmap: 0x6000660060000000,
    },
    Symbol {
        ch: '\u{281b}',
        bitmap: 0x6600660000000000,
    },
    Symbol {
        ch: '\u{281d}',
        bitmap: 0x6600060060000000,
    },
    Symbol {
        ch: '\u{281e}',
        bitmap: 0x0600660060000000,
    },
    Symbol {
        ch: '\u{2827}',
        bitmap: 0x6000600066000000,
    },
    Symbol {
        ch: '\u{282b}',
        bitmap: 0x6600600006000000,
    },
    Symbol {
        ch: '\u{282d}',
        bitmap: 0x6600000066000000,
    },
    Symbol {
        ch: '\u{282e}',
        bitmap: 0x0600600066000000,
    },
    Symbol {
        ch: '\u{2833}',
        bitmap: 0x6000660006000000,
    },
    Symbol {
        ch: '\u{2835}',
        bitmap: 0x6000060066000000,
    },
    Symbol {
        ch: '\u{2836}',
        bitmap: 0x0000660066000000,
    },
    Symbol {
        ch: '\u{2839}',
        bitmap: 0x6600060006000000,
    },
    Symbol {
        ch: '\u{283a}',
        bitmap: 0x0600660006000000,
    },
    Symbol {
        ch: '\u{283c}',
        bitmap: 0x0600060066000000,
    },
    Symbol {
        ch: '\u{2847}',
        bitmap: 0x6000600060006000,
    },
    Symbol {
        ch: '\u{284b}',
        bitmap: 0x6600600000006000,
    },
    Symbol {
        ch: '\u{284d}',
        bitmap: 0x6600000060006000,
    },
    Symbol {
        ch: '\u{284e}',
        bitmap: 0x0600600060006000,
    },
    Symbol {
        ch: '\u{2853}',
        bitmap: 0x6000660000006000,
    },
    Symbol {
        ch: '\u{2855}',
        bitmap: 0x6000060060006000,
    },
    Symbol {
        ch: '\u{2856}',
        bitmap: 0x0000660060006000,
    },
    Symbol {
        ch: '\u{2859}',
        bitmap: 0x6600060000006000,
    },
    Symbol {
        ch: '\u{285a}',
        bitmap: 0x0600660000006000,
    },
    Symbol {
        ch: '\u{285c}',
        bitmap: 0x0600060060006000,
    },
    Symbol {
        ch: '\u{2863}',
        bitmap: 0x6000600006006000,
    },
    Symbol {
        ch: '\u{2865}',
        bitmap: 0x6000000066006000,
    },
    Symbol {
        ch: '\u{2866}',
        bitmap: 0x0000600066006000,
    },
    Symbol {
        ch: '\u{2869}',
        bitmap: 0x6600000006006000,
    },
    Symbol {
        ch: '\u{286a}',
        bitmap: 0x0600600006006000,
    },
    Symbol {
        ch: '\u{286c}',
        bitmap: 0x0600000066006000,
    },
    Symbol {
        ch: '\u{2871}',
        bitmap: 0x6000060006006000,
    },
    Symbol {
        ch: '\u{2872}',
        bitmap: 0x0000660006006000,
    },
    Symbol {
        ch: '\u{2874}',
        bitmap: 0x0000060066006000,
    },
    Symbol {
        ch: '\u{2878}',
        bitmap: 0x0600060006006000,
    },
    Symbol {
        ch: '\u{2887}',
        bitmap: 0x6000600060000600,
    },
    Symbol {
        ch: '\u{288b}',
        bitmap: 0x6600600000000600,
    },
    Symbol {
        ch: '\u{288d}',
        bitmap: 0x6600000060000600,
    },
    Symbol {
        ch: '\u{288e}',
        bitmap: 0x0600600060000600,
    },
    Symbol {
        ch: '\u{2893}',
        bitmap: 0x6000660000000600,
    },
    Symbol {
        ch: '\u{2895}',
        bitmap: 0x6000060060000600,
    },
    Symbol {
        ch: '\u{2896}',
        bitmap: 0x0000660060000600,
    },
    Symbol {
        ch: '\u{2899}',
        bitmap: 0x6600060000000600,
    },
    Symbol {
        ch: '\u{289a}',
        bitmap: 0x0600660000000600,
    },
    Symbol {
        ch: '\u{289c}',
        bitmap: 0x0600060060000600,
    },
    Symbol {
        ch: '\u{28a3}',
        bitmap: 0x6000600006000600,
    },
    Symbol {
        ch: '\u{28a5}',
        bitmap: 0x6000000066000600,
    },
    Symbol {
        ch: '\u{28a6}',
        bitmap: 0x0000600066000600,
    },
    Symbol {
        ch: '\u{28a9}',
        bitmap: 0x6600000006000600,
    },
    Symbol {
        ch: '\u{28aa}',
        bitmap: 0x0600600006000600,
    },
    Symbol {
        ch: '\u{28ac}',
        bitmap: 0x0600000066000600,
    },
    Symbol {
        ch: '\u{28b1}',
        bitmap: 0x6000060006000600,
    },
    Symbol {
        ch: '\u{28b2}',
        bitmap: 0x0000660006000600,
    },
    Symbol {
        ch: '\u{28b4}',
        bitmap: 0x0000060066000600,
    },
    Symbol {
        ch: '\u{28b8}',
        bitmap: 0x0600060006000600,
    },
    Symbol {
        ch: '\u{28c3}',
        bitmap: 0x6000600000006600,
    },
    Symbol {
        ch: '\u{28c5}',
        bitmap: 0x6000000060006600,
    },
    Symbol {
        ch: '\u{28c6}',
        bitmap: 0x0000600060006600,
    },
    Symbol {
        ch: '\u{28c9}',
        bitmap: 0x6600000000006600,
    },
    Symbol {
        ch: '\u{28ca}',
        bitmap: 0x0600600000006600,
    },
    Symbol {
        ch: '\u{28cc}',
        bitmap: 0x0600000060006600,
    },
    Symbol {
        ch: '\u{28d1}',
        bitmap: 0x6000060000006600,
    },
    Symbol {
        ch: '\u{28d2}',
        bitmap: 0x0000660000006600,
    },
    Symbol {
        ch: '\u{28d4}',
        bitmap: 0x0000060060006600,
    },
    Symbol {
        ch: '\u{28d8}',
        bitmap: 0x0600060000006600,
    },
    Symbol {
        ch: '\u{28e1}',
        bitmap: 0x6000000006006600,
    },
    Symbol {
        ch: '\u{28e2}',
        bitmap: 0x0000600006006600,
    },
    Symbol {
        ch: '\u{28e4}',
        bitmap: 0x0000000066006600,
    },
    Symbol {
        ch: '\u{28e8}',
        bitmap: 0x0600000006006600,
    },
    Symbol {
        ch: '\u{28f0}',
        bitmap: 0x0000060006006600,
    },
    Symbol {
        ch: '\u{1fb03}',
        bitmap: 0x000000f0f0000000,
    },
    Symbol {
        ch: '\u{1fb07}',
        bitmap: 0x0000000f0f000000,
    },
    Symbol {
        ch: '\u{1fb3c}',
        bitmap: 0x000000000080e0f0,
    },
    Symbol {
        ch: '\u{1fb47}',
        bitmap: 0x000000000001070f,
    },
    Symbol {
        ch: '\u{1fb57}',
        bitmap: 0xf0e0800000000000,
    },
    Symbol {
        ch: '\u{1fb70}',
        bitmap: 0x4040404040404040,
    },
    Symbol {
        ch: '\u{1fb71}',
        bitmap: 0x2020202020202020,
    },
    Symbol {
        ch: '\u{1fb72}',
        bitmap: 0x1010101010101010,
    },
    Symbol {
        ch: '\u{1fb73}',
        bitmap: 0x0808080808080808,
    },
    Symbol {
        ch: '\u{1fb74}',
        bitmap: 0x0404040404040404,
    },
    Symbol {
        ch: '\u{1fb75}',
        bitmap: 0x0202020202020202,
    },
    Symbol {
        ch: '\u{1fb76}',
        bitmap: 0x00ff000000000000,
    },
    Symbol {
        ch: '\u{1fb77}',
        bitmap: 0x0000ff0000000000,
    },
    Symbol {
        ch: '\u{1fb78}',
        bitmap: 0x000000ff00000000,
    },
    Symbol {
        ch: '\u{1fb79}',
        bitmap: 0x00000000ff000000,
    },
    Symbol {
        ch: '\u{1fb7a}',
        bitmap: 0x0000000000ff0000,
    },
    Symbol {
        ch: '\u{1fb7b}',
        bitmap: 0x000000000000ff00,
    },
    Symbol {
        ch: '\u{1fba4}',
        bitmap: 0x1020408080402010,
    },
    Symbol {
        ch: '\u{1fba5}',
        bitmap: 0x0804020101020408,
    },
    Symbol {
        ch: '\u{1fba6}',
        bitmap: 0x0000000081422418,
    },
    Symbol {
        ch: '\u{1fba7}',
        bitmap: 0x1824428100000000,
    },
    Symbol {
        ch: '\u{1fba8}',
        bitmap: 0x1020408001020408,
    },
    Symbol {
        ch: '\u{1fba9}',
        bitmap: 0x0804020180402010,
    },
    Symbol {
        ch: '\u{3c}',
        bitmap: 0x0004083060180400,
    },
    Symbol {
        ch: '\u{3e}',
        bitmap: 0x004020180c304000,
    },
    Symbol {
        ch: '\u{6c}',
        bitmap: 0x0030101010103800,
    },
    Symbol {
        ch: '\u{72}',
        bitmap: 0x0000007e40404000,
    },
    Symbol {
        ch: '\u{b2}',
        bitmap: 0x1824083c00000000,
    },
    Symbol {
        ch: '\u{ec}',
        bitmap: 0x0020103010103800,
    },
    Symbol {
        ch: '\u{ed}',
        bitmap: 0x0008103010103800,
    },
    Symbol {
        ch: '\u{ef}',
        bitmap: 0x0048003010103800,
    },
    Symbol {
        ch: '\u{12d}',
        bitmap: 0x0048003010103800,
    },
    Symbol {
        ch: '\u{164}',
        bitmap: 0x3c00101010101000,
    },
    Symbol {
        ch: '\u{237}',
        bitmap: 0x0000000c04044438,
    },
    Symbol {
        ch: '\u{2518}',
        bitmap: 0x08080808f8000000,
    },
    Symbol {
        ch: '\u{49}',
        bitmap: 0x0038101010103800,
    },
    Symbol {
        ch: '\u{5b}',
        bitmap: 0x0038202020203800,
    },
    Symbol {
        ch: '\u{5d}',
        bitmap: 0x0038080808083800,
    },
    Symbol {
        ch: '\u{6a}',
        bitmap: 0x0004000c04044438,
    },
    Symbol {
        ch: '\u{76}',
        bitmap: 0x0000004266241800,
    },
    Symbol {
        ch: '\u{78}',
        bitmap: 0x000000423c244200,
    },
    Symbol {
        ch: '\u{b3}',
        bitmap: 0x380c043c00000000,
    },
    Symbol {
        ch: '\u{d7}',
        bitmap: 0x0000006618244200,
    },
    Symbol {
        ch: '\u{12b}',
        bitmap: 0x0000383010103800,
    },
    Symbol {
        ch: '\u{12f}',
        bitmap: 0x001000301010380c,
    },
    Symbol {
        ch: '\u{13c}',
        bitmap: 0x0030101010103820,
    },
    Symbol {
        ch: '\u{155}',
        bitmap: 0x0008007e40404000,
    },
    Symbol {
        ch: '\u{178}',
        bitmap: 0x4400824428101000,
    },
    Symbol {
        ch: '\u{38e}',
        bitmap: 0xc000824428101000,
    },
    Symbol {
        ch: '\u{390}',
        bitmap: 0x1068003010100c00,
    },
    Symbol {
        ch: '\u{399}',
        bitmap: 0x0038101010103800,
    },
    Symbol {
        ch: '\u{3ab}',
        bitmap: 0x4400824428101000,
    },
    Symbol {
        ch: '\u{3bd}',
        bitmap: 0x0000004266241800,
    },
    Symbol {
        ch: '\u{3c5}',
        bitmap: 0x0000004242423c00,
    },
    Symbol {
        ch: '\u{3c7}',
        bitmap: 0x0000004224182442,
    },
    Symbol {
        ch: '\u{3f3}',
        bitmap: 0x0004000c04044438,
    },
    Symbol {
        ch: '\u{281f}',
        bitmap: 0x6600660060000000,
    },
    Symbol {
        ch: '\u{282f}',
        bitmap: 0x6600600066000000,
    },
    Symbol {
        ch: '\u{2837}',
        bitmap: 0x6000660066000000,
    },
    Symbol {
        ch: '\u{283b}',
        bitmap: 0x6600660006000000,
    },
    Symbol {
        ch: '\u{283d}',
        bitmap: 0x6600060066000000,
    },
    Symbol {
        ch: '\u{283e}',
        bitmap: 0x0600660066000000,
    },
    Symbol {
        ch: '\u{284f}',
        bitmap: 0x6600600060006000,
    },
    Symbol {
        ch: '\u{2857}',
        bitmap: 0x6000660060006000,
    },
    Symbol {
        ch: '\u{285b}',
        bitmap: 0x6600660000006000,
    },
    Symbol {
        ch: '\u{285d}',
        bitmap: 0x6600060060006000,
    },
    Symbol {
        ch: '\u{285e}',
        bitmap: 0x0600660060006000,
    },
    Symbol {
        ch: '\u{2867}',
        bitmap: 0x6000600066006000,
    },
    Symbol {
        ch: '\u{286b}',
        bitmap: 0x6600600006006000,
    },
    Symbol {
        ch: '\u{286d}',
        bitmap: 0x6600000066006000,
    },
    Symbol {
        ch: '\u{286e}',
        bitmap: 0x0600600066006000,
    },
    Symbol {
        ch: '\u{2873}',
        bitmap: 0x6000660006006000,
    },
    Symbol {
        ch: '\u{2875}',
        bitmap: 0x6000060066006000,
    },
    Symbol {
        ch: '\u{2876}',
        bitmap: 0x0000660066006000,
    },
    Symbol {
        ch: '\u{2879}',
        bitmap: 0x6600060006006000,
    },
    Symbol {
        ch: '\u{287a}',
        bitmap: 0x0600660006006000,
    },
    Symbol {
        ch: '\u{287c}',
        bitmap: 0x0600060066006000,
    },
    Symbol {
        ch: '\u{288f}',
        bitmap: 0x6600600060000600,
    },
    Symbol {
        ch: '\u{2897}',
        bitmap: 0x6000660060000600,
    },
    Symbol {
        ch: '\u{289b}',
        bitmap: 0x6600660000000600,
    },
    Symbol {
        ch: '\u{289d}',
        bitmap: 0x6600060060000600,
    },
    Symbol {
        ch: '\u{289e}',
        bitmap: 0x0600660060000600,
    },
    Symbol {
        ch: '\u{28a7}',
        bitmap: 0x6000600066000600,
    },
    Symbol {
        ch: '\u{28ab}',
        bitmap: 0x6600600006000600,
    },
    Symbol {
        ch: '\u{28ad}',
        bitmap: 0x6600000066000600,
    },
    Symbol {
        ch: '\u{28ae}',
        bitmap: 0x0600600066000600,
    },
    Symbol {
        ch: '\u{28b3}',
        bitmap: 0x6000660006000600,
    },
    Symbol {
        ch: '\u{28b5}',
        bitmap: 0x6000060066000600,
    },
    Symbol {
        ch: '\u{28b6}',
        bitmap: 0x0000660066000600,
    },
    Symbol {
        ch: '\u{28b9}',
        bitmap: 0x6600060006000600,
    },
    Symbol {
        ch: '\u{28ba}',
        bitmap: 0x0600660006000600,
    },
    Symbol {
        ch: '\u{28bc}',
        bitmap: 0x0600060066000600,
    },
    Symbol {
        ch: '\u{28c7}',
        bitmap: 0x6000600060006600,
    },
    Symbol {
        ch: '\u{28cb}',
        bitmap: 0x6600600000006600,
    },
    Symbol {
        ch: '\u{28cd}',
        bitmap: 0x6600000060006600,
    },
    Symbol {
        ch: '\u{28ce}',
        bitmap: 0x0600600060006600,
    },
    Symbol {
        ch: '\u{28d3}',
        bitmap: 0x6000660000006600,
    },
    Symbol {
        ch: '\u{28d5}',
        bitmap: 0x6000060060006600,
    },
    Symbol {
        ch: '\u{28d6}',
        bitmap: 0x0000660060006600,
    },
    Symbol {
        ch: '\u{28d9}',
        bitmap: 0x6600060000006600,
    },
    Symbol {
        ch: '\u{28da}',
        bitmap: 0x0600660000006600,
    },
    Symbol {
        ch: '\u{28dc}',
        bitmap: 0x0600060060006600,
    },
    Symbol {
        ch: '\u{28e3}',
        bitmap: 0x6000600006006600,
    },
    Symbol {
        ch: '\u{28e5}',
        bitmap: 0x6000000066006600,
    },
    Symbol {
        ch: '\u{28e6}',
        bitmap: 0x0000600066006600,
    },
    Symbol {
        ch: '\u{28e9}',
        bitmap: 0x6600000006006600,
    },
    Symbol {
        ch: '\u{28ea}',
        bitmap: 0x0600600006006600,
    },
    Symbol {
        ch: '\u{28ec}',
        bitmap: 0x0600000066006600,
    },
    Symbol {
        ch: '\u{28f1}',
        bitmap: 0x6000060006006600,
    },
    Symbol {
        ch: '\u{28f2}',
        bitmap: 0x0000660006006600,
    },
    Symbol {
        ch: '\u{28f4}',
        bitmap: 0x0000060066006600,
    },
    Symbol {
        ch: '\u{28f8}',
        bitmap: 0x0600060006006600,
    },
    Symbol {
        ch: '\u{37}',
        bitmap: 0x007e020408101000,
    },
    Symbol {
        ch: '\u{3f}',
        bitmap: 0x003c424608000800,
    },
    Symbol {
        ch: '\u{4a}',
        bitmap: 0x000e040404443800,
    },
    Symbol {
        ch: '\u{4c}',
        bitmap: 0x0040404040407e00,
    },
    Symbol {
        ch: '\u{59}',
        bitmap: 0x0082446c10101000,
    },
    Symbol {
        ch: '\u{75}',
        bitmap: 0x0000004242423e00,
    },
    Symbol {
        ch: '\u{bf}',
        bitmap: 0x0010001062423c00,
    },
    Symbol {
        ch: '\u{ee}',
        bitmap: 0x0030483010103800,
    },
    Symbol {
        ch: '\u{130}',
        bitmap: 0x1038101010103800,
    },
    Symbol {
        ch: '\u{13a}',
        bitmap: 0x1830101010103800,
    },
    Symbol {
        ch: '\u{140}',
        bitmap: 0x0030101111103800,
    },
    Symbol {
        ch: '\u{142}',
        bitmap: 0x0030101830103800,
    },
    Symbol {
        ch: '\u{157}',
        bitmap: 0x0000007e40406040,
    },
    Symbol {
        ch: '\u{1d0}',
        bitmap: 0x0048303010103800,
    },
    Symbol {
        ch: '\u{1f0}',
        bitmap: 0x0012000c04044438,
    },
    Symbol {
        ch: '\u{393}',
        bitmap: 0x007e404040404000,
    },
    Symbol {
        ch: '\u{3a5}',
        bitmap: 0x0082446c10101000,
    },
    Symbol {
        ch: '\u{3ba}',
        bitmap: 0x0000004678484200,
    },
    Symbol {
        ch: '\u{3c4}',
        bitmap: 0x000000fe10100c00,
    },
    Symbol {
        ch: '\u{250d}',
        bitmap: 0x0000000f0f080808,
    },
    Symbol {
        ch: '\u{250e}',
        bitmap: 0x000000001f181818,
    },
    Symbol {
        ch: '\u{2512}',
        bitmap: 0x00000000f8181818,
    },
    Symbol {
        ch: '\u{2515}',
        bitmap: 0x0808080f0f000000,
    },
    Symbol {
        ch: '\u{251c}',
        bitmap: 0x080808080f080808,
    },
    Symbol {
        ch: '\u{252c}',
        bitmap: 0x00000000ff080808,
    },
    Symbol {
        ch: '\u{2a}',
        bitmap: 0x0000003c7e240000,
    },
    Symbol {
        ch: '\u{31}',
        bitmap: 0x0018280808083e00,
    },
    Symbol {
        ch: '\u{3d}',
        bitmap: 0x0000007e7e000000,
    },
    Symbol {
        ch: '\u{54}',
        bitmap: 0x00fe101010101000,
    },
    Symbol {
        ch: '\u{56}',
        bitmap: 0x0042424224241800,
    },
    Symbol {
        ch: '\u{58}',
        bitmap: 0x0042241818244200,
    },
    Symbol {
        ch: '\u{66}',
        bitmap: 0x000e107c10101000,
    },
    Symbol {
        ch: '\u{6e}',
        bitmap: 0x0000007e42424200,
    },
    Symbol {
        ch: '\u{74}',
        bitmap: 0x0010107c10100e00,
    },
    Symbol {
        ch: '\u{b1}',
        bitmap: 0x000000107c107c00,
    },
    Symbol {
        ch: '\u{cc}',
        bitmap: 0x3038101010103800,
    },
    Symbol {
        ch: '\u{cd}',
        bitmap: 0x1838101010103800,
    },
    Symbol {
        ch: '\u{cf}',
        bitmap: 0x4438101010103800,
    },
    Symbol {
        ch: '\u{12e}',
        bitmap: 0x003810101010380c,
    },
    Symbol {
        ch: '\u{134}',
        bitmap: 0x0c12040404443800,
    },
    Symbol {
        ch: '\u{138}',
        bitmap: 0x00000046784c4200,
    },
    Symbol {
        ch: '\u{139}',
        bitmap: 0x6000404040407e00,
    },
    Symbol {
        ch: '\u{13b}',
        bitmap: 0x0040404040407e20,
    },
    Symbol {
        ch: '\u{176}',
        bitmap: 0x3c00824428101000,
    },
    Symbol {
        ch: '\u{38a}',
        bitmap: 0xc038101010103800,
    },
    Symbol {
        ch: '\u{3a4}',
        bitmap: 0x00fe101010101000,
    },
    Symbol {
        ch: '\u{3a7}',
        bitmap: 0x0042241818244200,
    },
    Symbol {
        ch: '\u{3aa}',
        bitmap: 0x4438101010103800,
    },
    Symbol {
        ch: '\u{3bb}',
        bitmap: 0x002010286c448200,
    },
    Symbol {
        ch: '\u{3c0}',
        bitmap: 0x0000007e42424200,
    },
    Symbol {
        ch: '\u{3cb}',
        bitmap: 0x0024004242423c00,
    },
    Symbol {
        ch: '\u{3cd}',
        bitmap: 0x0008104242423c00,
    },
    Symbol {
        ch: '\u{3f0}',
        bitmap: 0x000000e618308600,
    },
    Symbol {
        ch: '\u{2190}',
        bitmap: 0x0010307e30100000,
    },
    Symbol {
        ch: '\u{2191}',
        bitmap: 0x0010387c10101000,
    },
    Symbol {
        ch: '\u{2192}',
        bitmap: 0x00080c7e0c080000,
    },
    Symbol {
        ch: '\u{2193}',
        bitmap: 0x001010107c381000,
    },
    Symbol {
        ch: '\u{2505}',
        bitmap: 0x000000dbdb000000,
    },
    Symbol {
        ch: '\u{2507}',
        bitmap: 0x1818001818001818,
    },
    Symbol {
        ch: '\u{2524}',
        bitmap: 0x08080808f8080808,
    },
    Symbol {
        ch: '\u{2534}',
        bitmap: 0x08080808ff000000,
    },
    Symbol {
        ch: '\u{254d}',
        bitmap: 0x000000e7e7000000,
    },
    Symbol {
        ch: '\u{254f}',
        bitmap: 0x1818180000181818,
    },
    Symbol {
        ch: '\u{257c}',
        bitmap: 0x0000000fff000000,
    },
    Symbol {
        ch: '\u{257d}',
        bitmap: 0x0808080818181818,
    },
    Symbol {
        ch: '\u{257e}',
        bitmap: 0x000000f0ff000000,
    },
    Symbol {
        ch: '\u{257f}',
        bitmap: 0x1818181808080808,
    },
    Symbol {
        ch: '\u{283f}',
        bitmap: 0x6600660066000000,
    },
    Symbol {
        ch: '\u{285f}',
        bitmap: 0x6600660060006000,
    },
    Symbol {
        ch: '\u{286f}',
        bitmap: 0x6600600066006000,
    },
    Symbol {
        ch: '\u{2877}',
        bitmap: 0x6000660066006000,
    },
    Symbol {
        ch: '\u{287b}',
        bitmap: 0x6600660006006000,
    },
    Symbol {
        ch: '\u{287d}',
        bitmap: 0x6600060066006000,
    },
    Symbol {
        ch: '\u{287e}',
        bitmap: 0x0600660066006000,
    },
    Symbol {
        ch: '\u{289f}',
        bitmap: 0x6600660060000600,
    },
    Symbol {
        ch: '\u{28af}',
        bitmap: 0x6600600066000600,
    },
    Symbol {
        ch: '\u{28b7}',
        bitmap: 0x6000660066000600,
    },
    Symbol {
        ch: '\u{28bb}',
        bitmap: 0x6600660006000600,
    },
    Symbol {
        ch: '\u{28bd}',
        bitmap: 0x6600060066000600,
    },
    Symbol {
        ch: '\u{28be}',
        bitmap: 0x0600660066000600,
    },
    Symbol {
        ch: '\u{28cf}',
        bitmap: 0x6600600060006600,
    },
    Symbol {
        ch: '\u{28d7}',
        bitmap: 0x6000660060006600,
    },
    Symbol {
        ch: '\u{28db}',
        bitmap: 0x6600660000006600,
    },
    Symbol {
        ch: '\u{28dd}',
        bitmap: 0x6600060060006600,
    },
    Symbol {
        ch: '\u{28de}',
        bitmap: 0x0600660060006600,
    },
    Symbol {
        ch: '\u{28e7}',
        bitmap: 0x6000600066006600,
    },
    Symbol {
        ch: '\u{28eb}',
        bitmap: 0x6600600006006600,
    },
    Symbol {
        ch: '\u{28ed}',
        bitmap: 0x6600000066006600,
    },
    Symbol {
        ch: '\u{28ee}',
        bitmap: 0x0600600066006600,
    },
    Symbol {
        ch: '\u{28f3}',
        bitmap: 0x6000660006006600,
    },
    Symbol {
        ch: '\u{28f5}',
        bitmap: 0x6000060066006600,
    },
    Symbol {
        ch: '\u{28f6}',
        bitmap: 0x0000660066006600,
    },
    Symbol {
        ch: '\u{28f9}',
        bitmap: 0x6600060006006600,
    },
    Symbol {
        ch: '\u{28fa}',
        bitmap: 0x0600660006006600,
    },
    Symbol {
        ch: '\u{28fc}',
        bitmap: 0x0600060066006600,
    },
    Symbol {
        ch: '\u{1fb00}',
        bitmap: 0xf0f0f00000000000,
    },
    Symbol {
        ch: '\u{1fb01}',
        bitmap: 0x0f0f0f0000000000,
    },
    Symbol {
        ch: '\u{1fb0f}',
        bitmap: 0x0000000000f0f0f0,
    },
    Symbol {
        ch: '\u{1fb1e}',
        bitmap: 0x00000000000f0f0f,
    },
    Symbol {
        ch: '\u{1fb3e}',
        bitmap: 0x00000080c0c0e0f0,
    },
    Symbol {
        ch: '\u{1fb49}',
        bitmap: 0x000000010303070f,
    },
    Symbol {
        ch: '\u{1fb59}',
        bitmap: 0xf0e0e08080000000,
    },
    Symbol {
        ch: '\u{1fb64}',
        bitmap: 0x0f07030301000000,
    },
    Symbol {
        ch: '\u{1fbaa}',
        bitmap: 0x0804020181422418,
    },
    Symbol {
        ch: '\u{1fbab}',
        bitmap: 0x1020408081422418,
    },
    Symbol {
        ch: '\u{1fbac}',
        bitmap: 0x1824428101020408,
    },
    Symbol {
        ch: '\u{1fbad}',
        bitmap: 0x1824428180402010,
    },
    Symbol {
        ch: '\u{63}',
        bitmap: 0x0000007e40423c00,
    },
    Symbol {
        ch: '\u{77}',
        bitmap: 0x0000008292927c00,
    },
    Symbol {
        ch: '\u{b5}',
        bitmap: 0x0000004242467a40,
    },
    Symbol {
        ch: '\u{f9}',
        bitmap: 0x0010084242423e00,
    },
    Symbol {
        ch: '\u{fa}',
        bitmap: 0x0008104242423e00,
    },
    Symbol {
        ch: '\u{fc}',
        bitmap: 0x0024004242423e00,
    },
    Symbol {
        ch: '\u{128}',
        bitmap: 0x7e00101010103800,
    },
    Symbol {
        ch: '\u{129}',
        bitmap: 0x0036483010103800,
    },
    Symbol {
        ch: '\u{135}',
        bitmap: 0x000c120c04044438,
    },
    Symbol {
        ch: '\u{13e}',
        bitmap: 0x7830101010103800,
    },
    Symbol {
        ch: '\u{13f}',
        bitmap: 0x0040404444407e00,
    },
    Symbol {
        ch: '\u{141}',
        bitmap: 0x00404060c0407e00,
    },
    Symbol {
        ch: '\u{144}',
        bitmap: 0x0008007e42424200,
    },
    Symbol {
        ch: '\u{159}',
        bitmap: 0x0024187e40404000,
    },
    Symbol {
        ch: '\u{163}',
        bitmap: 0x0010107c10100e08,
    },
    Symbol {
        ch: '\u{173}',
        bitmap: 0x0000004242423e03,
    },
    Symbol {
        ch: '\u{19e}',
        bitmap: 0x0000007e42424202,
    },
    Symbol {
        ch: '\u{21b}',
        bitmap: 0x0010107c10100e04,
    },
    Symbol {
        ch: '\u{254}',
        bitmap: 0x0000007e02423c00,
    },
    Symbol {
        ch: '\u{272}',
        bitmap: 0x0000007e42424280,
    },
    Symbol {
        ch: '\u{39b}',
        bitmap: 0x0010286c44828200,
    },
    Symbol {
        ch: '\u{3b7}',
        bitmap: 0x0000007e42424202,
    },
    Symbol {
        ch: '\u{3bc}',
        bitmap: 0x0000004242467a40,
    },
    Symbol {
        ch: '\u{3c3}',
        bitmap: 0x0000007e44443800,
    },
    Symbol {
        ch: '\u{3f2}',
        bitmap: 0x0000007e40423c00,
    },
    Symbol {
        ch: '\u{2511}',
        bitmap: 0x000000f8f8080808,
    },
    Symbol {
        ch: '\u{2516}',
        bitmap: 0x181818181f000000,
    },
    Symbol {
        ch: '\u{2519}',
        bitmap: 0x080808f8f8000000,
    },
    Symbol {
        ch: '\u{251a}',
        bitmap: 0x18181818f8000000,
    },
    Symbol {
        ch: '\u{43}',
        bitmap: 0x003c424040423c00,
    },
    Symbol {
        ch: '\u{46}',
        bitmap: 0x007e407840404000,
    },
    Symbol {
        ch: '\u{55}',
        bitmap: 0x0042424242423c00,
    },
    Symbol {
        ch: '\u{68}',
        bitmap: 0x0040407e42424200,
    },
    Symbol {
        ch: '\u{6b}',
        bitmap: 0x0040404678484600,
    },
    Symbol {
        ch: '\u{6f}',
        bitmap: 0x0000007e42423c00,
    },
    Symbol {
        ch: '\u{a4}',
        bitmap: 0x0000447c44384400,
    },
    Symbol {
        ch: '\u{ab}',
        bitmap: 0x00000036d86c1200,
    },
    Symbol {
        ch: '\u{bb}',
        bitmap: 0x000000d8366c9000,
    },
    Symbol {
        ch: '\u{ce}',
        bitmap: 0x3c38101010103800,
    },
    Symbol {
        ch: '\u{dd}',
        bitmap: 0x1c82446c10101000,
    },
    Symbol {
        ch: '\u{e7}',
        bitmap: 0x0000007e40423c20,
    },
    Symbol {
        ch: '\u{107}',
        bitmap: 0x0008007e40423c00,
    },
    Symbol {
        ch: '\u{10b}',
        bitmap: 0x0010007e40423c00,
    },
    Symbol {
        ch: '\u{12c}',
        bitmap: 0x3c38101010103800,
    },
    Symbol {
        ch: '\u{146}',
        bitmap: 0x0000007e42425220,
    },
    Symbol {
        ch: '\u{149}',
        bitmap: 0x4040007e42424200,
    },
    Symbol {
        ch: '\u{14b}',
        bitmap: 0x0000007e4242420c,
    },
    Symbol {
        ch: '\u{162}',
        bitmap: 0x00fe101010101810,
    },
    Symbol {
        ch: '\u{167}',
        bitmap: 0x0010107c38100e00,
    },
    Symbol {
        ch: '\u{186}',
        bitmap: 0x003c420202423c00,
    },
    Symbol {
        ch: '\u{1cf}',
        bitmap: 0x3c38101010103800,
    },
    Symbol {
        ch: '\u{21a}',
        bitmap: 0x00fe101010101810,
    },
    Symbol {
        ch: '\u{3b1}',
        bitmap: 0x0000007e44443a00,
    },
    Symbol {
        ch: '\u{3bf}',
        bitmap: 0x0000007e42423c00,
    },
    Symbol {
        ch: '\u{3c2}',
        bitmap: 0x0000007e40403c06,
    },
    Symbol {
        ch: '\u{3c9}',
        bitmap: 0x000000c692926c00,
    },
    Symbol {
        ch: '\u{251d}',
        bitmap: 0x0808080f0f080808,
    },
    Symbol {
        ch: '\u{2530}',
        bitmap: 0x00000000ff181818,
    },
    Symbol {
        ch: '\u{287f}',
        bitmap: 0x6600660066006000,
    },
    Symbol {
        ch: '\u{28bf}',
        bitmap: 0x6600660066000600,
    },
    Symbol {
        ch: '\u{28df}',
        bitmap: 0x6600660060006600,
    },
    Symbol {
        ch: '\u{28ef}',
        bitmap: 0x6600600066006600,
    },
    Symbol {
        ch: '\u{28f7}',
        bitmap: 0x6000660066006600,
    },
    Symbol {
        ch: '\u{28fb}',
        bitmap: 0x6600660006006600,
    },
    Symbol {
        ch: '\u{28fd}',
        bitmap: 0x6600060066006600,
    },
    Symbol {
        ch: '\u{28fe}',
        bitmap: 0x0600660066006600,
    },
    Symbol {
        ch: '\u{1fb48}',
        bitmap: 0x0000000000031f7f,
    },
    Symbol {
        ch: '\u{34}',
        bitmap: 0x00061a227e020200,
    },
    Symbol {
        ch: '\u{65}',
        bitmap: 0x0000007e5a403c00,
    },
    Symbol {
        ch: '\u{79}',
        bitmap: 0x0000004242423e3c,
    },
    Symbol {
        ch: '\u{aa}',
        bitmap: 0x380464387c000000,
    },
    Symbol {
        ch: '\u{ba}',
        bitmap: 0x384444387c000000,
    },
    Symbol {
        ch: '\u{c7}',
        bitmap: 0x003c424040423c20,
    },
    Symbol {
        ch: '\u{fb}',
        bitmap: 0x0018244242423e00,
    },
    Symbol {
        ch: '\u{109}',
        bitmap: 0x0018007e40423c00,
    },
    Symbol {
        ch: '\u{10a}',
        bitmap: 0x103c424040423c00,
    },
    Symbol {
        ch: '\u{12a}',
        bitmap: 0x7c38101010103800,
    },
    Symbol {
        ch: '\u{13d}',
        bitmap: 0x2458404040407e00,
    },
    Symbol {
        ch: '\u{165}',
        bitmap: 0x3c00107c10100e00,
    },
    Symbol {
        ch: '\u{16b}',
        bitmap: 0x00003c4242423e00,
    },
    Symbol {
        ch: '\u{16d}',
        bitmap: 0x0024184242423e00,
    },
    Symbol {
        ch: '\u{16f}',
        bitmap: 0x0018184242423e00,
    },
    Symbol {
        ch: '\u{171}',
        bitmap: 0x0012244242423e00,
    },
    Symbol {
        ch: '\u{192}',
        bitmap: 0x000c127c101010e0,
    },
    Symbol {
        ch: '\u{1d4}',
        bitmap: 0x0024184242423e00,
    },
    Symbol {
        ch: '\u{258}',
        bitmap: 0x0000007e5a023c00,
    },
    Symbol {
        ch: '\u{3ae}',
        bitmap: 0x0008107e42424202,
    },
    Symbol {
        ch: '\u{3c8}',
        bitmap: 0x0000009292927c10,
    },
    Symbol {
        ch: '\u{3cc}',
        bitmap: 0x0008007e42423c00,
    },
    Symbol {
        ch: '\u{251f}',
        bitmap: 0x080808081f181818,
    },
    Symbol {
        ch: '\u{2527}',
        bitmap: 0x08080808f8181818,
    },
    Symbol {
        ch: '\u{252e}',
        bitmap: 0x0000000fff080808,
    },
    Symbol {
        ch: '\u{2536}',
        bitmap: 0x0808080fff000000,
    },
    Symbol {
        ch: '\u{253c}',
        bitmap: 0x08080808ff080808,
    },
    Symbol {
        ch: '\u{1fb3d}',
        bitmap: 0x0000000000c0f8ff,
    },
    Symbol {
        ch: '\u{1fb63}',
        bitmap: 0xff1f030000000000,
    },
    Symbol {
        ch: '\u{1fb7c}',
        bitmap: 0x80808080808080ff,
    },
    Symbol {
        ch: '\u{1fb7d}',
        bitmap: 0xff80808080808080,
    },
    Symbol {
        ch: '\u{1fb7e}',
        bitmap: 0xff01010101010101,
    },
    Symbol {
        ch: '\u{1fb7f}',
        bitmap: 0x01010101010101ff,
    },
    Symbol {
        ch: '\u{25}',
        bitmap: 0x00646818302c4c00,
    },
    Symbol {
        ch: '\u{26}',
        bitmap: 0x001824384a443a00,
    },
    Symbol {
        ch: '\u{33}',
        bitmap: 0x003c421c02423c00,
    },
    Symbol {
        ch: '\u{48}',
        bitmap: 0x0042427e42424200,
    },
    Symbol {
        ch: '\u{4b}',
        bitmap: 0x00424c70704c4200,
    },
    Symbol {
        ch: '\u{4e}',
        bitmap: 0x004262524a464200,
    },
    Symbol {
        ch: '\u{4f}',
        bitmap: 0x003c424242423c00,
    },
    Symbol {
        ch: '\u{50}',
        bitmap: 0x007c42427c404000,
    },
    Symbol {
        ch: '\u{6d}',
        bitmap: 0x000000fe92929200,
    },
    Symbol {
        ch: '\u{70}',
        bitmap: 0x0000007e42427c40,
    },
    Symbol {
        ch: '\u{71}',
        bitmap: 0x0000007e42423e02,
    },
    Symbol {
        ch: '\u{7a}',
        bitmap: 0x0000007e0c307e00,
    },
    Symbol {
        ch: '\u{a3}',
        bitmap: 0x0018247820207e00,
    },
    Symbol {
        ch: '\u{dc}',
        bitmap: 0x2442424242423c00,
    },
    Symbol {
        ch: '\u{de}',
        bitmap: 0x00407c42427c4000,
    },
    Symbol {
        ch: '\u{f2}',
        bitmap: 0x0010087e42423c00,
    },
    Symbol {
        ch: '\u{f3}',
        bitmap: 0x0008107e42423c00,
    },
    Symbol {
        ch: '\u{f4}',
        bitmap: 0x0018007e42423c00,
    },
    Symbol {
        ch: '\u{f6}',
        bitmap: 0x0024007e42423c00,
    },
    Symbol {
        ch: '\u{117}',
        bitmap: 0x0010007e5a403c00,
    },
    Symbol {
        ch: '\u{127}',
        bitmap: 0x0040707e42424200,
    },
    Symbol {
        ch: '\u{137}',
        bitmap: 0x00404046784c5220,
    },
    Symbol {
        ch: '\u{148}',
        bitmap: 0x0024187e42424200,
    },
    Symbol {
        ch: '\u{14d}',
        bitmap: 0x0000187e42423c00,
    },
    Symbol {
        ch: '\u{14e}',
        bitmap: 0x2418424242423c00,
    },
    Symbol {
        ch: '\u{150}',
        bitmap: 0x3600424242423c00,
    },
    Symbol {
        ch: '\u{151}',
        bitmap: 0x0012007e42423c00,
    },
    Symbol {
        ch: '\u{166}',
        bitmap: 0x00fe107c10101000,
    },
    Symbol {
        ch: '\u{169}',
        bitmap: 0x00320c4242423e00,
    },
    Symbol {
        ch: '\u{170}',
        bitmap: 0x3600424242423c00,
    },
    Symbol {
        ch: '\u{172}',
        bitmap: 0x0042424242423c06,
    },
    Symbol {
        ch: '\u{17c}',
        bitmap: 0x0010007e18207e00,
    },
    Symbol {
        ch: '\u{190}',
        bitmap: 0x003c423840423c00,
    },
    Symbol {
        ch: '\u{1d2}',
        bitmap: 0x0024007e42423c00,
    },
    Symbol {
        ch: '\u{1eb}',
        bitmap: 0x0000007e42423c06,
    },
    Symbol {
        ch: '\u{232}',
        bitmap: 0x7c82446c10101000,
    },
    Symbol {
        ch: '\u{259}',
        bitmap: 0x0000003e7a423c00,
    },
    Symbol {
        ch: '\u{25b}',
        bitmap: 0x0000007e78423c00,
    },
    Symbol {
        ch: '\u{292}',
        bitmap: 0x0000007e041c027c,
    },
    Symbol {
        ch: '\u{397}',
        bitmap: 0x0042427e42424200,
    },
    Symbol {
        ch: '\u{39a}',
        bitmap: 0x00424c70704c4200,
    },
    Symbol {
        ch: '\u{39d}',
        bitmap: 0x004242724e424200,
    },
    Symbol {
        ch: '\u{39f}',
        bitmap: 0x003c424242423c00,
    },
    Symbol {
        ch: '\u{3a0}',
        bitmap: 0x007e424242424200,
    },
    Symbol {
        ch: '\u{3a1}',
        bitmap: 0x007c42427c404000,
    },
    Symbol {
        ch: '\u{3a9}',
        bitmap: 0x003c424242246600,
    },
    Symbol {
        ch: '\u{3ac}',
        bitmap: 0x0008107e44443a00,
    },
    Symbol {
        ch: '\u{3b0}',
        bitmap: 0x0834244242423c00,
    },
    Symbol {
        ch: '\u{3b5}',
        bitmap: 0x0000007e78423c00,
    },
    Symbol {
        ch: '\u{3c1}',
        bitmap: 0x0000007e42427c40,
    },
    Symbol {
        ch: '\u{3ce}',
        bitmap: 0x000810c692926c00,
    },
    Symbol {
        ch: '\u{3f5}',
        bitmap: 0x0000003e7c403e00,
    },
    Symbol {
        ch: '\u{3f6}',
        bitmap: 0x0000007c3e027c00,
    },
    Symbol {
        ch: '\u{2501}',
        bitmap: 0x000000ffff000000,
    },
    Symbol {
        ch: '\u{2503}',
        bitmap: 0x1818181818181818,
    },
    Symbol {
        ch: '\u{250f}',
        bitmap: 0x0000001f1f181818,
    },
    Symbol {
        ch: '\u{2513}',
        bitmap: 0x000000f8f8181818,
    },
    Symbol {
        ch: '\u{2517}',
        bitmap: 0x1818181f1f000000,
    },
    Symbol {
        ch: '\u{251b}',
        bitmap: 0x181818f8f8000000,
    },
    Symbol {
        ch: '\u{251e}',
        bitmap: 0x181818181f080808,
    },
    Symbol {
        ch: '\u{2525}',
        bitmap: 0x080808f8f8080808,
    },
    Symbol {
        ch: '\u{2526}',
        bitmap: 0x18181818f8080808,
    },
    Symbol {
        ch: '\u{252d}',
        bitmap: 0x000000f8ff080808,
    },
    Symbol {
        ch: '\u{2535}',
        bitmap: 0x080808f8ff000000,
    },
    Symbol {
        ch: '\u{2538}',
        bitmap: 0x18181818ff000000,
    },
    Symbol {
        ch: '\u{2573}',
        bitmap: 0x8142241818244281,
    },
    Symbol {
        ch: '\u{2582}',
        bitmap: 0x000000000000ffff,
    },
    Symbol {
        ch: '\u{258e}',
        bitmap: 0xc0c0c0c0c0c0c0c0,
    },
    Symbol {
        ch: '\u{2591}',
        bitmap: 0x8822882288228822,
    },
    Symbol {
        ch: '\u{2596}',
        bitmap: 0x00000000f0f0f0f0,
    },
    Symbol {
        ch: '\u{2597}',
        bitmap: 0x000000000f0f0f0f,
    },
    Symbol {
        ch: '\u{2598}',
        bitmap: 0xf0f0f0f000000000,
    },
    Symbol {
        ch: '\u{259d}',
        bitmap: 0x0f0f0f0f00000000,
    },
    Symbol {
        ch: '\u{28ff}',
        bitmap: 0x6600660066006600,
    },
    Symbol {
        ch: '\u{1fb0b}',
        bitmap: 0x000000ffff000000,
    },
    Symbol {
        ch: '\u{1fb40}',
        bitmap: 0x008080c0c0e0e0f0,
    },
    Symbol {
        ch: '\u{1fb58}',
        bitmap: 0xfff8e00000000000,
    },
    Symbol {
        ch: '\u{1fb6c}',
        bitmap: 0x0080c0e0f0e0c080,
    },
    Symbol {
        ch: '\u{1fb6e}',
        bitmap: 0x000103070f070301,
    },
    Symbol {
        ch: '\u{1fb80}',
        bitmap: 0xff000000000000ff,
    },
    Symbol {
        ch: '\u{1fb82}',
        bitmap: 0xffff000000000000,
    },
    Symbol {
        ch: '\u{1fb87}',
        bitmap: 0x0303030303030303,
    },
    Symbol {
        ch: '\u{1fbae}',
        bitmap: 0x1824428181422418,
    },
    Symbol {
        ch: '\u{32}',
        bitmap: 0x003c420618207e00,
    },
    Symbol {
        ch: '\u{47}',
        bitmap: 0x003c42404e423c00,
    },
    Symbol {
        ch: '\u{4d}',
        bitmap: 0x00c6aa9282828200,
    },
    Symbol {
        ch: '\u{51}',
        bitmap: 0x003c424242423c02,
    },
    Symbol {
        ch: '\u{57}',
        bitmap: 0x0082828292aac600,
    },
    Symbol {
        ch: '\u{62}',
        bitmap: 0x0040407e42427c00,
    },
    Symbol {
        ch: '\u{64}',
        bitmap: 0x0002027e42423e00,
    },
    Symbol {
        ch: '\u{73}',
        bitmap: 0x0000007e7c027c00,
    },
    Symbol {
        ch: '\u{d9}',
        bitmap: 0x3842424242423c00,
    },
    Symbol {
        ch: '\u{da}',
        bitmap: 0x1c42424242423c00,
    },
    Symbol {
        ch: '\u{e8}',
        bitmap: 0x0010087e5a403c00,
    },
    Symbol {
        ch: '\u{e9}',
        bitmap: 0x0008107e5a403c00,
    },
    Symbol {
        ch: '\u{ea}',
        bitmap: 0x0018007e5a403c00,
    },
    Symbol {
        ch: '\u{eb}',
        bitmap: 0x0024007e5a403c00,
    },
    Symbol {
        ch: '\u{fd}',
        bitmap: 0x0008104242423e3c,
    },
    Symbol {
        ch: '\u{ff}',
        bitmap: 0x0024004242423e3c,
    },
    Symbol {
        ch: '\u{106}',
        bitmap: 0x1c3c424040423c00,
    },
    Symbol {
        ch: '\u{10d}',
        bitmap: 0x0024187e40423c00,
    },
    Symbol {
        ch: '\u{119}',
        bitmap: 0x0000007e5a403c06,
    },
    Symbol {
        ch: '\u{133}',
        bitmap: 0x004200c64242f20c,
    },
    Symbol {
        ch: '\u{175}',
        bitmap: 0x0018248292927c00,
    },
    Symbol {
        ch: '\u{17a}',
        bitmap: 0x0008107e18207e00,
    },
    Symbol {
        ch: '\u{19d}',
        bitmap: 0x004242724e424280,
    },
    Symbol {
        ch: '\u{1b6}',
        bitmap: 0x0000007e3c107e00,
    },
    Symbol {
        ch: '\u{1b7}',
        bitmap: 0x007e041c02423c00,
    },
    Symbol {
        ch: '\u{39c}',
        bitmap: 0x00c6aa9282828200,
    },
    Symbol {
        ch: '\u{3b6}',
        bitmap: 0x007e083040403c06,
    },
    Symbol {
        ch: '\u{3b8}',
        bitmap: 0x0038447c44443800,
    },
    Symbol {
        ch: '\u{3d1}',
        bitmap: 0x0038443e84443800,
    },
    Symbol {
        ch: '\u{23}',
        bitmap: 0x002424766e242400,
    },
    Symbol {
        ch: '\u{36}',
        bitmap: 0x003c407c42423c00,
    },
    Symbol {
        ch: '\u{38}',
        bitmap: 0x003c423c42423c00,
    },
    Symbol {
        ch: '\u{39}',
        bitmap: 0x003c42423e023c00,
    },
    Symbol {
        ch: '\u{41}',
        bitmap: 0x003c42427e424200,
    },
    Symbol {
        ch: '\u{44}',
        bitmap: 0x007c424242427c00,
    },
    Symbol {
        ch: '\u{53}',
        bitmap: 0x003c427c02423c00,
    },
    Symbol {
        ch: '\u{5a}',
        bitmap: 0x007e020c30407e00,
    },
    Symbol {
        ch: '\u{61}',
        bitmap: 0x0000003e7e423e00,
    },
    Symbol {
        ch: '\u{a5}',
        bitmap: 0x008244387c7c1000,
    },
    Symbol {
        ch: '\u{d6}',
        bitmap: 0x243c424242423c00,
    },
    Symbol {
        ch: '\u{db}',
        bitmap: 0x3c42424242423c00,
    },
    Symbol {
        ch: '\u{f1}',
        bitmap: 0x00324c7e42424200,
    },
    Symbol {
        ch: '\u{fe}',
        bitmap: 0x0040407e42427c40,
    },
    Symbol {
        ch: '\u{108}',
        bitmap: 0x3c3c424040423c00,
    },
    Symbol {
        ch: '\u{10c}',
        bitmap: 0x3c3c424040423c00,
    },
    Symbol {
        ch: '\u{113}',
        bitmap: 0x0000387e5a403c00,
    },
    Symbol {
        ch: '\u{120}',
        bitmap: 0x103c42404e423c00,
    },
    Symbol {
        ch: '\u{122}',
        bitmap: 0x003c42404e423c20,
    },
    Symbol {
        ch: '\u{124}',
        bitmap: 0x3c0042427e424200,
    },
    Symbol {
        ch: '\u{125}',
        bitmap: 0x1e40407e42424200,
    },
    Symbol {
        ch: '\u{136}',
        bitmap: 0x00424c70704c5220,
    },
    Symbol {
        ch: '\u{145}',
        bitmap: 0x004242724e425220,
    },
    Symbol {
        ch: '\u{14a}',
        bitmap: 0x004242724e42420c,
    },
    Symbol {
        ch: '\u{14f}',
        bitmap: 0x0024187e42423c00,
    },
    Symbol {
        ch: '\u{15f}',
        bitmap: 0x0000007e7c027c20,
    },
    Symbol {
        ch: '\u{168}',
        bitmap: 0x324c424242423c00,
    },
    Symbol {
        ch: '\u{16a}',
        bitmap: 0x3c42424242423c00,
    },
    Symbol {
        ch: '\u{16c}',
        bitmap: 0x245a424242423c00,
    },
    Symbol {
        ch: '\u{16e}',
        bitmap: 0x3c18424242423c00,
    },
    Symbol {
        ch: '\u{1d3}',
        bitmap: 0x3c42424242423c00,
    },
    Symbol {
        ch: '\u{1e9}',
        bitmap: 0x3c404046784c4200,
    },
    Symbol {
        ch: '\u{1ea}',
        bitmap: 0x003c424242423c06,
    },
    Symbol {
        ch: '\u{219}',
        bitmap: 0x0000007e7c027c20,
    },
    Symbol {
        ch: '\u{389}',
        bitmap: 0xc042427e42424200,
    },
    Symbol {
        ch: '\u{38c}',
        bitmap: 0xc03c424242423c00,
    },
    Symbol {
        ch: '\u{38f}',
        bitmap: 0xc03c424242246600,
    },
    Symbol {
        ch: '\u{391}',
        bitmap: 0x003c42427e424200,
    },
    Symbol {
        ch: '\u{394}',
        bitmap: 0x0010286c4482fe00,
    },
    Symbol {
        ch: '\u{396}',
        bitmap: 0x007e020c30407e00,
    },
    Symbol {
        ch: '\u{398}',
        bitmap: 0x003c425a42423c00,
    },
    Symbol {
        ch: '\u{3a3}',
        bitmap: 0x007e201818207e00,
    },
    Symbol {
        ch: '\u{3a8}',
        bitmap: 0x00929292927c1000,
    },
    Symbol {
        ch: '\u{3ad}',
        bitmap: 0x0008107e78423c00,
    },
    Symbol {
        ch: '\u{3be}',
        bitmap: 0x003e403c40403c06,
    },
    Symbol {
        ch: '\u{3c6}',
        bitmap: 0x000000de92927c10,
    },
    Symbol {
        ch: '\u{253e}',
        bitmap: 0x0808080fff080808,
    },
    Symbol {
        ch: '\u{2541}',
        bitmap: 0x08080808ff181818,
    },
    Symbol {
        ch: '\u{1fb5b}',
        bitmap: 0xf0f0e0e0c0808000,
    },
    Symbol {
        ch: '\u{35}',
        bitmap: 0x007e407c02423c00,
    },
    Symbol {
        ch: '\u{45}',
        bitmap: 0x007e407840407e00,
    },
    Symbol {
        ch: '\u{52}',
        bitmap: 0x007c42427c4c4200,
    },
    Symbol {
        ch: '\u{67}',
        bitmap: 0x0000007e42423e3c,
    },
    Symbol {
        ch: '\u{a2}',
        bitmap: 0x000010fe90927c10,
    },
    Symbol {
        ch: '\u{bc}',
        bitmap: 0x60222418668a0e02,
    },
    Symbol {
        ch: '\u{d2}',
        bitmap: 0x383c424242423c00,
    },
    Symbol {
        ch: '\u{d3}',
        bitmap: 0x1c3c424242423c00,
    },
    Symbol {
        ch: '\u{df}',
        bitmap: 0x0038447c42625c00,
    },
    Symbol {
        ch: '\u{e6}',
        bitmap: 0x0000007e729e6c00,
    },
    Symbol {
        ch: '\u{f0}',
        bitmap: 0x00282c7e42423c00,
    },
    Symbol {
        ch: '\u{f8}',
        bitmap: 0x0000027e5a62bc00,
    },
    Symbol {
        ch: '\u{111}',
        bitmap: 0x00020e7e42423e00,
    },
    Symbol {
        ch: '\u{115}',
        bitmap: 0x0024187e5a403c00,
    },
    Symbol {
        ch: '\u{11b}',
        bitmap: 0x0024187e5a403c00,
    },
    Symbol {
        ch: '\u{143}',
        bitmap: 0x1c4242724e424200,
    },
    Symbol {
        ch: '\u{15b}',
        bitmap: 0x0004087e7c027c00,
    },
    Symbol {
        ch: '\u{15e}',
        bitmap: 0x003c427c02423c20,
    },
    Symbol {
        ch: '\u{174}',
        bitmap: 0x3c00828292aac600,
    },
    Symbol {
        ch: '\u{177}',
        bitmap: 0x0018244242423e3c,
    },
    Symbol {
        ch: '\u{17b}',
        bitmap: 0x107e020c30407e00,
    },
    Symbol {
        ch: '\u{17e}',
        bitmap: 0x0024187e18207e00,
    },
    Symbol {
        ch: '\u{18e}',
        bitmap: 0x007e021e02027e00,
    },
    Symbol {
        ch: '\u{18f}',
        bitmap: 0x003c027e42423c00,
    },
    Symbol {
        ch: '\u{1ed}',
        bitmap: 0x0000387e42423c06,
    },
    Symbol {
        ch: '\u{1ee}',
        bitmap: 0x1c3e041c02423c00,
    },
    Symbol {
        ch: '\u{1f4}',
        bitmap: 0x0c3c42404e423c00,
    },
    Symbol {
        ch: '\u{218}',
        bitmap: 0x003c427c02423c20,
    },
    Symbol {
        ch: '\u{233}',
        bitmap: 0x00003c4242423e3c,
    },
    Symbol {
        ch: '\u{395}',
        bitmap: 0x007e407840407e00,
    },
    Symbol {
        ch: '\u{3f1}',
        bitmap: 0x0000007e42427c3c,
    },
    Symbol {
        ch: '\u{2520}',
        bitmap: 0x181818181f181818,
    },
    Symbol {
        ch: '\u{2521}',
        bitmap: 0x1818181f1f080808,
    },
    Symbol {
        ch: '\u{2522}',
        bitmap: 0x0808081f1f181818,
    },
    Symbol {
        ch: '\u{2528}',
        bitmap: 0x18181818f8181818,
    },
    Symbol {
        ch: '\u{2529}',
        bitmap: 0x181818f8f8080808,
    },
    Symbol {
        ch: '\u{252a}',
        bitmap: 0x080808f8f8181818,
    },
    Symbol {
        ch: '\u{252f}',
        bitmap: 0x000000ffff080808,
    },
    Symbol {
        ch: '\u{2531}',
        bitmap: 0x000000f8ff181818,
    },
    Symbol {
        ch: '\u{2532}',
        bitmap: 0x0000001fff181818,
    },
    Symbol {
        ch: '\u{2537}',
        bitmap: 0x080808ffff000000,
    },
    Symbol {
        ch: '\u{2539}',
        bitmap: 0x181818f8ff000000,
    },
    Symbol {
        ch: '\u{253a}',
        bitmap: 0x1818181fff000000,
    },
    Symbol {
        ch: '\u{253d}',
        bitmap: 0x080808f8ff080808,
    },
    Symbol {
        ch: '\u{2540}',
        bitmap: 0x18181818ff080808,
    },
    Symbol {
        ch: '\u{30}',
        bitmap: 0x003c424e72423c00,
    },
    Symbol {
        ch: '\u{a7}',
        bitmap: 0x3844304c64184438,
    },
    Symbol {
        ch: '\u{b6}',
        bitmap: 0x007e929272121200,
    },
    Symbol {
        ch: '\u{bd}',
        bitmap: 0x602224186c92081e,
    },
    Symbol {
        ch: '\u{c4}',
        bitmap: 0x243c42427e424200,
    },
    Symbol {
        ch: '\u{d4}',
        bitmap: 0x3c3c424242423c00,
    },
    Symbol {
        ch: '\u{e0}',
        bitmap: 0x0010083e7e423e00,
    },
    Symbol {
        ch: '\u{e1}',
        bitmap: 0x0008103e7e423e00,
    },
    Symbol {
        ch: '\u{e2}',
        bitmap: 0x0018003e7e423e00,
    },
    Symbol {
        ch: '\u{e4}',
        bitmap: 0x0024003e7e423e00,
    },
    Symbol {
        ch: '\u{f5}',
        bitmap: 0x00324c7e42423c00,
    },
    Symbol {
        ch: '\u{101}',
        bitmap: 0x0000183e7e423e00,
    },
    Symbol {
        ch: '\u{103}',
        bitmap: 0x0024003e7e423e00,
    },
    Symbol {
        ch: '\u{105}',
        bitmap: 0x0000003e7e423e03,
    },
    Symbol {
        ch: '\u{10e}',
        bitmap: 0x247c424242427c00,
    },
    Symbol {
        ch: '\u{116}',
        bitmap: 0x107e407840407e00,
    },
    Symbol {
        ch: '\u{121}',
        bitmap: 0x0008007e42423e3c,
    },
    Symbol {
        ch: '\u{126}',
        bitmap: 0x0042e77e42424200,
    },
    Symbol {
        ch: '\u{132}',
        bitmap: 0x00e742424252ec00,
    },
    Symbol {
        ch: '\u{147}',
        bitmap: 0x245a42724e424200,
    },
    Symbol {
        ch: '\u{14c}',
        bitmap: 0x3c3c424242423c00,
    },
    Symbol {
        ch: '\u{153}',
        bitmap: 0x000000fe9e907e00,
    },
    Symbol {
        ch: '\u{15a}',
        bitmap: 0x183c42403e423c00,
    },
    Symbol {
        ch: '\u{179}',
        bitmap: 0x187e020c30407e00,
    },
    Symbol {
        ch: '\u{1d1}',
        bitmap: 0x3c3c424242423c00,
    },
    Symbol {
        ch: '\u{1e3}',
        bitmap: 0x0000187e7e906c00,
    },
    Symbol {
        ch: '\u{1e4}',
        bitmap: 0x003c42404e4f3c00,
    },
    Symbol {
        ch: '\u{1e8}',
        bitmap: 0x3c424c70704c4200,
    },
    Symbol {
        ch: '\u{1ef}',
        bitmap: 0x0024187e041c027c,
    },
    Symbol {
        ch: '\u{1fd}',
        bitmap: 0x0008107e7e906c00,
    },
    Symbol {
        ch: '\u{386}',
        bitmap: 0xc03c42427e424200,
    },
    Symbol {
        ch: '\u{3b2}',
        bitmap: 0x0038447c42427c40,
    },
    Symbol {
        ch: '\u{3b4}',
        bitmap: 0x003e087e42423c00,
    },
    Symbol {
        ch: '\u{3d5}',
        bitmap: 0x000010fe92927c10,
    },
    Symbol {
        ch: '\u{3f4}',
        bitmap: 0x003c427e42423c00,
    },
    Symbol {
        ch: '\u{1fb04}',
        bitmap: 0xf0f0f0f0f0000000,
    },
    Symbol {
        ch: '\u{1fb05}',
        bitmap: 0x0f0f0ff0f0000000,
    },
    Symbol {
        ch: '\u{1fb08}',
        bitmap: 0xf0f0f00f0f000000,
    },
    Symbol {
        ch: '\u{1fb09}',
        bitmap: 0x0f0f0f0f0f000000,
    },
    Symbol {
        ch: '\u{1fb13}',
        bitmap: 0x000000f0f0f0f0f0,
    },
    Symbol {
        ch: '\u{1fb16}',
        bitmap: 0x0000000f0ff0f0f0,
    },
    Symbol {
        ch: '\u{1fb22}',
        bitmap: 0x000000f0f00f0f0f,
    },
    Symbol {
        ch: '\u{1fb26}',
        bitmap: 0x0000000f0f0f0f0f,
    },
    Symbol {
        ch: '\u{1fb4b}',
        bitmap: 0x0101030307070f0f,
    },
    Symbol {
        ch: '\u{1fb66}',
        bitmap: 0x0f0f070703030101,
    },
    Symbol {
        ch: '\u{1fb6d}',
        bitmap: 0xff7e3c1800000000,
    },
    Symbol {
        ch: '\u{1fb6f}',
        bitmap: 0x00000000183c7eff,
    },
    Symbol {
        ch: '\u{42}',
        bitmap: 0x007c427c42427c00,
    },
    Symbol {
        ch: '\u{c0}',
        bitmap: 0x383c42427e424200,
    },
    Symbol {
        ch: '\u{c1}',
        bitmap: 0x1c3c42427e424200,
    },
    Symbol {
        ch: '\u{cb}',
        bitmap: 0x247e404078407e00,
    },
    Symbol {
        ch: '\u{d0}',
        bitmap: 0x007c42f242427c00,
    },
    Symbol {
        ch: '\u{102}',
        bitmap: 0x2c3c42427e424200,
    },
    Symbol {
        ch: '\u{104}',
        bitmap: 0x003c42427e424207,
    },
    Symbol {
        ch: '\u{10f}',
        bitmap: 0x241a027e42423e00,
    },
    Symbol {
        ch: '\u{110}',
        bitmap: 0x007c42f242427c00,
    },
    Symbol {
        ch: '\u{118}',
        bitmap: 0x007e407840407e03,
    },
    Symbol {
        ch: '\u{11c}',
        bitmap: 0x3c3c42404e423c00,
    },
    Symbol {
        ch: '\u{11e}',
        bitmap: 0x3c3c42404e423c00,
    },
    Symbol {
        ch: '\u{123}',
        bitmap: 0x0408007e42423e3c,
    },
    Symbol {
        ch: '\u{156}',
        bitmap: 0x007c42427c485620,
    },
    Symbol {
        ch: '\u{15d}',
        bitmap: 0x0018247e7c027c00,
    },
    Symbol {
        ch: '\u{161}',
        bitmap: 0x0024187e7c027c00,
    },
    Symbol {
        ch: '\u{1e6}',
        bitmap: 0x3c3c42404e423c00,
    },
    Symbol {
        ch: '\u{1f5}',
        bitmap: 0x0004087e42423e3c,
    },
    Symbol {
        ch: '\u{1ff}',
        bitmap: 0x0008127e5a62bc00,
    },
    Symbol {
        ch: '\u{388}',
        bitmap: 0xc07e407840407e00,
    },
    Symbol {
        ch: '\u{392}',
        bitmap: 0x007c427c42427c00,
    },
    Symbol {
        ch: '\u{1fb65}',
        bitmap: 0x7f3f0f0701000000,
    },
    Symbol {
        ch: '\u{c2}',
        bitmap: 0x3c3c42427e424200,
    },
    Symbol {
        ch: '\u{c5}',
        bitmap: 0x3c3c42427e424200,
    },
    Symbol {
        ch: '\u{c8}',
        bitmap: 0x387e404078407e00,
    },
    Symbol {
        ch: '\u{c9}',
        bitmap: 0x1c7e404078407e00,
    },
    Symbol {
        ch: '\u{d1}',
        bitmap: 0x7e4242724e424200,
    },
    Symbol {
        ch: '\u{d5}',
        bitmap: 0x7e3c424242423c00,
    },
    Symbol {
        ch: '\u{d8}',
        bitmap: 0x003c434e72c23c00,
    },
    Symbol {
        ch: '\u{e5}',
        bitmap: 0x0018183e7e423e00,
    },
    Symbol {
        ch: '\u{100}',
        bitmap: 0x3c3c42427e424200,
    },
    Symbol {
        ch: '\u{152}',
        bitmap: 0x007e909c90907e00,
    },
    Symbol {
        ch: '\u{154}',
        bitmap: 0x1c7c42427c484600,
    },
    Symbol {
        ch: '\u{15c}',
        bitmap: 0x3c3c42403e423c00,
    },
    Symbol {
        ch: '\u{160}',
        bitmap: 0x3c3c42403e423c00,
    },
    Symbol {
        ch: '\u{17d}',
        bitmap: 0x3c7e020c30407e00,
    },
    Symbol {
        ch: '\u{1b5}',
        bitmap: 0x007e047e30407e00,
    },
    Symbol {
        ch: '\u{1cd}',
        bitmap: 0x3c3c42427e424200,
    },
    Symbol {
        ch: '\u{1ce}',
        bitmap: 0x0024183e7e423e00,
    },
    Symbol {
        ch: '\u{1e5}',
        bitmap: 0x0000007e4f423e3c,
    },
    Symbol {
        ch: '\u{1ec}',
        bitmap: 0x3c3c424242423c06,
    },
    Symbol {
        ch: '\u{3a6}',
        bitmap: 0x007c929292927c00,
    },
    Symbol {
        ch: '\u{2523}',
        bitmap: 0x1818181f1f181818,
    },
    Symbol {
        ch: '\u{252b}',
        bitmap: 0x181818f8f8181818,
    },
    Symbol {
        ch: '\u{2533}',
        bitmap: 0x000000ffff181818,
    },
    Symbol {
        ch: '\u{253b}',
        bitmap: 0x181818ffff000000,
    },
    Symbol {
        ch: '\u{253f}',
        bitmap: 0x080808ffff080808,
    },
    Symbol {
        ch: '\u{2542}',
        bitmap: 0x18181818ff181818,
    },
    Symbol {
        ch: '\u{2543}',
        bitmap: 0x181818f8ff080808,
    },
    Symbol {
        ch: '\u{2544}',
        bitmap: 0x1818181fff080808,
    },
    Symbol {
        ch: '\u{2545}',
        bitmap: 0x080808f8ff181818,
    },
    Symbol {
        ch: '\u{2546}',
        bitmap: 0x0808081fff181818,
    },
    Symbol {
        ch: '\u{1fb98}',
        bitmap: 0x9249249249249249,
    },
    Symbol {
        ch: '\u{1fb99}',
        bitmap: 0x4992244992244992,
    },
    Symbol {
        ch: '\u{24}',
        bitmap: 0x10107c907e127c10,
    },
    Symbol {
        ch: '\u{c6}',
        bitmap: 0x007e90fc90909e00,
    },
    Symbol {
        ch: '\u{ca}',
        bitmap: 0x3c7e404078407e00,
    },
    Symbol {
        ch: '\u{112}',
        bitmap: 0x3c7e407840407e00,
    },
    Symbol {
        ch: '\u{114}',
        bitmap: 0x3c7e407840407e00,
    },
    Symbol {
        ch: '\u{11a}',
        bitmap: 0x3c7e407840407e00,
    },
    Symbol {
        ch: '\u{11d}',
        bitmap: 0x0018247e42423e3c,
    },
    Symbol {
        ch: '\u{11f}',
        bitmap: 0x0024187e42423e3c,
    },
    Symbol {
        ch: '\u{158}',
        bitmap: 0x3c7c42427c484600,
    },
    Symbol {
        ch: '\u{1e7}',
        bitmap: 0x0024187e42423e3c,
    },
    Symbol {
        ch: '\u{be}',
        bitmap: 0xf062e418668a0e02,
    },
    Symbol {
        ch: '\u{c3}',
        bitmap: 0x7e3c42427e424200,
    },
    Symbol {
        ch: '\u{e3}',
        bitmap: 0x00324c3e7e423e00,
    },
    Symbol {
        ch: '\u{1fe}',
        bitmap: 0x0c3c474a72c23c00,
    },
    Symbol {
        ch: '\u{2583}',
        bitmap: 0x0000000000ffffff,
    },
    Symbol {
        ch: '\u{258d}',
        bitmap: 0xe0e0e0e0e0e0e0e0,
    },
    Symbol {
        ch: '\u{1fb02}',
        bitmap: 0xffffff0000000000,
    },
    Symbol {
        ch: '\u{1fb10}',
        bitmap: 0xf0f0f00000f0f0f0,
    },
    Symbol {
        ch: '\u{1fb11}',
        bitmap: 0x0f0f0f0000f0f0f0,
    },
    Symbol {
        ch: '\u{1fb1f}',
        bitmap: 0xf0f0f000000f0f0f,
    },
    Symbol {
        ch: '\u{1fb20}',
        bitmap: 0x0f0f0f00000f0f0f,
    },
    Symbol {
        ch: '\u{1fb2d}',
        bitmap: 0x0000000000ffffff,
    },
    Symbol {
        ch: '\u{1fb4a}',
        bitmap: 0x00000001071f7fff,
    },
    Symbol {
        ch: '\u{1fb83}',
        bitmap: 0xffffff0000000000,
    },
    Symbol {
        ch: '\u{1fb88}',
        bitmap: 0x0707070707070707,
    },
    Symbol {
        ch: '\u{40}',
        bitmap: 0x007c82baa6987e00,
    },
    Symbol {
        ch: '\u{1fc}',
        bitmap: 0x0c7e9090fc909e00,
    },
    Symbol {
        ch: '\u{2547}',
        bitmap: 0x181818ffff080808,
    },
    Symbol {
        ch: '\u{2548}',
        bitmap: 0x080808ffff181818,
    },
    Symbol {
        ch: '\u{2549}',
        bitmap: 0x181818f8ff181818,
    },
    Symbol {
        ch: '\u{254a}',
        bitmap: 0x1818181fff181818,
    },
    Symbol {
        ch: '\u{1fb3f}',
        bitmap: 0x000000c0e0f8feff,
    },
    Symbol {
        ch: '\u{1fb5a}',
        bitmap: 0xfffef8e0c0000000,
    },
    Symbol {
        ch: '\u{25b2}',
        bitmap: 0x00183c7e7eff0000,
    },
    Symbol {
        ch: '\u{25bc}',
        bitmap: 0x00ff7e7e3c180000,
    },
    Symbol {
        ch: '\u{25cf}',
        bitmap: 0x003c7e7e7e3c0000,
    },
    Symbol {
        ch: '\u{ae}',
        bitmap: 0x0000ffa5b9a57e00,
    },
    Symbol {
        ch: '\u{a9}',
        bitmap: 0x0000ffbda19d7e00,
    },
    Symbol {
        ch: '\u{1e2}',
        bitmap: 0x7c7e90fc90909e00,
    },
    Symbol {
        ch: '\u{254b}',
        bitmap: 0x181818ffff181818,
    },
    Symbol {
        ch: '\u{1fb0c}',
        bitmap: 0xf0f0f0ffff000000,
    },
    Symbol {
        ch: '\u{1fb0d}',
        bitmap: 0x0f0f0fffff000000,
    },
    Symbol {
        ch: '\u{1fb1a}',
        bitmap: 0x000000fffff0f0f0,
    },
    Symbol {
        ch: '\u{1fb29}',
        bitmap: 0x000000ffff0f0f0f,
    },
    Symbol {
        ch: '\u{2580}',
        bitmap: 0xffffffff00000000,
    },
    Symbol {
        ch: '\u{2584}',
        bitmap: 0x00000000ffffffff,
    },
    Symbol {
        ch: '\u{258c}',
        bitmap: 0xf0f0f0f0f0f0f0f0,
    },
    Symbol {
        ch: '\u{2590}',
        bitmap: 0x0f0f0f0f0f0f0f0f,
    },
    Symbol {
        ch: '\u{2592}',
        bitmap: 0xaa55aa55aa55aa55,
    },
    Symbol {
        ch: '\u{259a}',
        bitmap: 0xf0f0f0f00f0f0f0f,
    },
    Symbol {
        ch: '\u{259e}',
        bitmap: 0x0f0f0f0ff0f0f0f0,
    },
    Symbol {
        ch: '\u{1fb06}',
        bitmap: 0xfffffff0f0000000,
    },
    Symbol {
        ch: '\u{1fb0a}',
        bitmap: 0xffffff0f0f000000,
    },
    Symbol {
        ch: '\u{1fb14}',
        bitmap: 0x0f0f0ff0f0f0f0f0,
    },
    Symbol {
        ch: '\u{1fb17}',
        bitmap: 0xf0f0f00f0ff0f0f0,
    },
    Symbol {
        ch: '\u{1fb18}',
        bitmap: 0x0f0f0f0f0ff0f0f0,
    },
    Symbol {
        ch: '\u{1fb23}',
        bitmap: 0xf0f0f0f0f00f0f0f,
    },
    Symbol {
        ch: '\u{1fb24}',
        bitmap: 0x0f0f0ff0f00f0f0f,
    },
    Symbol {
        ch: '\u{1fb27}',
        bitmap: 0xf0f0f00f0f0f0f0f,
    },
    Symbol {
        ch: '\u{1fb31}',
        bitmap: 0x000000f0f0ffffff,
    },
    Symbol {
        ch: '\u{1fb35}',
        bitmap: 0x0000000f0fffffff,
    },
    Symbol {
        ch: '\u{1fb46}',
        bitmap: 0x000000071fffffff,
    },
    Symbol {
        ch: '\u{1fb51}',
        bitmap: 0x000000e0f8ffffff,
    },
    Symbol {
        ch: '\u{1fb5c}',
        bitmap: 0xfffffff8e0000000,
    },
    Symbol {
        ch: '\u{1fb67}',
        bitmap: 0xffffff1f07000000,
    },
    Symbol {
        ch: '\u{1fb81}',
        bitmap: 0xff00ff00ff0000ff,
    },
    Symbol {
        ch: '\u{1fb95}',
        bitmap: 0xcccc3333cccc3333,
    },
    Symbol {
        ch: '\u{1fb96}',
        bitmap: 0x3333cccc3333cccc,
    },
    Symbol {
        ch: '\u{1fb97}',
        bitmap: 0x0000ffff0000ffff,
    },
    Symbol {
        ch: '\u{1fb9a}',
        bitmap: 0xfe7c3810081c3e7f,
    },
    Symbol {
        ch: '\u{1fb9b}',
        bitmap: 0x0183c7eff7e3c180,
    },
    Symbol {
        ch: '\u{1fb12}',
        bitmap: 0xffffff0000f0f0f0,
    },
    Symbol {
        ch: '\u{1fb21}',
        bitmap: 0xffffff00000f0f0f,
    },
    Symbol {
        ch: '\u{1fb2e}',
        bitmap: 0xf0f0f00000ffffff,
    },
    Symbol {
        ch: '\u{1fb2f}',
        bitmap: 0x0f0f0f0000ffffff,
    },
    Symbol {
        ch: '\u{1fb44}',
        bitmap: 0x0001030f3fffffff,
    },
    Symbol {
        ch: '\u{2585}',
        bitmap: 0x000000ffffffffff,
    },
    Symbol {
        ch: '\u{258b}',
        bitmap: 0xf8f8f8f8f8f8f8f8,
    },
    Symbol {
        ch: '\u{1fb0e}',
        bitmap: 0xffffffffff000000,
    },
    Symbol {
        ch: '\u{1fb1b}',
        bitmap: 0xf0f0f0fffff0f0f0,
    },
    Symbol {
        ch: '\u{1fb1c}',
        bitmap: 0x0f0f0ffffff0f0f0,
    },
    Symbol {
        ch: '\u{1fb2a}',
        bitmap: 0xf0f0f0ffff0f0f0f,
    },
    Symbol {
        ch: '\u{1fb2b}',
        bitmap: 0x0f0f0fffff0f0f0f,
    },
    Symbol {
        ch: '\u{1fb39}',
        bitmap: 0x000000ffffffffff,
    },
    Symbol {
        ch: '\u{1fb84}',
        bitmap: 0xffffffffff000000,
    },
    Symbol {
        ch: '\u{1fb89}',
        bitmap: 0x1f1f1f1f1f1f1f1f,
    },
    Symbol {
        ch: '\u{1fb15}',
        bitmap: 0xfffffff0f0f0f0f0,
    },
    Symbol {
        ch: '\u{1fb19}',
        bitmap: 0xffffff0f0ff0f0f0,
    },
    Symbol {
        ch: '\u{1fb25}',
        bitmap: 0xfffffff0f00f0f0f,
    },
    Symbol {
        ch: '\u{1fb28}',
        bitmap: 0xffffff0f0f0f0f0f,
    },
    Symbol {
        ch: '\u{1fb32}',
        bitmap: 0xf0f0f0f0f0ffffff,
    },
    Symbol {
        ch: '\u{1fb33}',
        bitmap: 0x0f0f0ff0f0ffffff,
    },
    Symbol {
        ch: '\u{1fb36}',
        bitmap: 0xf0f0f00f0fffffff,
    },
    Symbol {
        ch: '\u{1fb37}',
        bitmap: 0x0f0f0f0f0fffffff,
    },
    Symbol {
        ch: '\u{1fb45}',
        bitmap: 0x0f0f1f1f3f3f7f7f,
    },
    Symbol {
        ch: '\u{1fb4f}',
        bitmap: 0x80c0f0fcfeffffff,
    },
    Symbol {
        ch: '\u{1fb50}',
        bitmap: 0xf0f0f8f8fcfcfefe,
    },
    Symbol {
        ch: '\u{1fb56}',
        bitmap: 0x7f7f3f3f1f1f0f0f,
    },
    Symbol {
        ch: '\u{1fb61}',
        bitmap: 0xfefefcfcf8f8f0f0,
    },
    Symbol {
        ch: '\u{1fb69}',
        bitmap: 0x0081c3e7ffffffff,
    },
    Symbol {
        ch: '\u{1fb6b}',
        bitmap: 0xffffffffe7c38100,
    },
    Symbol {
        ch: '\u{1fb55}',
        bitmap: 0xffffff7f3f0f0701,
    },
    Symbol {
        ch: '\u{1fb60}',
        bitmap: 0xfffffffefcf0e080,
    },
    Symbol {
        ch: '\u{2586}',
        bitmap: 0x0000ffffffffffff,
    },
    Symbol {
        ch: '\u{258a}',
        bitmap: 0xfcfcfcfcfcfcfcfc,
    },
    Symbol {
        ch: '\u{2593}',
        bitmap: 0x77dd77dd77dd77dd,
    },
    Symbol {
        ch: '\u{2599}',
        bitmap: 0xf0f0f0f0ffffffff,
    },
    Symbol {
        ch: '\u{259b}',
        bitmap: 0xfffffffff0f0f0f0,
    },
    Symbol {
        ch: '\u{259c}',
        bitmap: 0xffffffff0f0f0f0f,
    },
    Symbol {
        ch: '\u{259f}',
        bitmap: 0x0f0f0f0fffffffff,
    },
    Symbol {
        ch: '\u{1fb30}',
        bitmap: 0xffffff0000ffffff,
    },
    Symbol {
        ch: '\u{1fb68}',
        bitmap: 0xff7f3f1f0f1f3f7f,
    },
    Symbol {
        ch: '\u{1fb6a}',
        bitmap: 0xfffefcf8f0f8fcfe,
    },
    Symbol {
        ch: '\u{1fb85}',
        bitmap: 0xffffffffffff0000,
    },
    Symbol {
        ch: '\u{1fb8a}',
        bitmap: 0x3f3f3f3f3f3f3f3f,
    },
    Symbol {
        ch: '\u{1fb42}',
        bitmap: 0x00073fffffffffff,
    },
    Symbol {
        ch: '\u{1fb53}',
        bitmap: 0xffffffffff3f0700,
    },
    Symbol {
        ch: '\u{1fb4d}',
        bitmap: 0x80e0fcffffffffff,
    },
    Symbol {
        ch: '\u{1fb5e}',
        bitmap: 0xfffffffffffce080,
    },
    Symbol {
        ch: '\u{1fb43}',
        bitmap: 0x0f1f1f3f7fffffff,
    },
    Symbol {
        ch: '\u{1fb1d}',
        bitmap: 0xfffffffffff0f0f0,
    },
    Symbol {
        ch: '\u{1fb2c}',
        bitmap: 0xffffffffff0f0f0f,
    },
    Symbol {
        ch: '\u{1fb3a}',
        bitmap: 0xf0f0f0ffffffffff,
    },
    Symbol {
        ch: '\u{1fb4e}',
        bitmap: 0xf0f8fcfcfeffffff,
    },
    Symbol {
        ch: '\u{1fb54}',
        bitmap: 0xffffff7f3f3f1f1f,
    },
    Symbol {
        ch: '\u{1fb5f}',
        bitmap: 0xfffffffefefcf8f0,
    },
    Symbol {
        ch: '\u{2587}',
        bitmap: 0x00ffffffffffffff,
    },
    Symbol {
        ch: '\u{2589}',
        bitmap: 0xfefefefefefefefe,
    },
    Symbol {
        ch: '\u{1fb34}',
        bitmap: 0xfffffff0f0ffffff,
    },
    Symbol {
        ch: '\u{1fb38}',
        bitmap: 0xffffff0f0fffffff,
    },
    Symbol {
        ch: '\u{1fb41}',
        bitmap: 0x0f1f7fffffffffff,
    },
    Symbol {
        ch: '\u{1fb52}',
        bitmap: 0xffffffffff7f1f0f,
    },
    Symbol {
        ch: '\u{1fb86}',
        bitmap: 0xffffffffffffff00,
    },
    Symbol {
        ch: '\u{1fb8b}',
        bitmap: 0x7f7f7f7f7f7f7f7f,
    },
    Symbol {
        ch: '\u{1fb4c}',
        bitmap: 0xf0fcfeffffffffff,
    },
    Symbol {
        ch: '\u{1fb5d}',
        bitmap: 0xfffffffffffefcf0,
    },
    Symbol {
        ch: '\u{2588}',
        bitmap: 0xffffffffffffffff,
    },
];
